select * from public.cnes_st cs;
select distinct coletres from public.cnes_st cs;

#---------------------------------------------------------
#Agrupar municipio, mes e ano - "mma"
#Calcular o número e percentual de "pf_pj" por "mma"


CREATE TABLE agrupado.cnes_st_agrupado1 as

SELECT 
  cs.codufmun,
  cs.nu_mes,
  cs.nu_ano,
  sum(CASE WHEN cs.pf_pj IS NULL THEN 1 ELSE 0 END) as ctg_pf_pj_null,
  sum(CASE WHEN cs.pf_pj = 'Física' THEN 1 ELSE 0 END) as ctg_pf_pj_fisica,
  sum(CASE WHEN cs.pf_pj = 'Jurídica' THEN 1 ELSE 0 END) as ctg_pf_pj_juridica,
  (sum(CASE WHEN cs.pf_pj IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_pf_pj_null,
  (sum(CASE WHEN cs.pf_pj = 'Física' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_pf_pj_fisica,
  (sum(CASE WHEN cs.pf_pj = 'Jurídica' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_pf_pj_juridica,  
  sum(CASE WHEN cs.niv_dep IS NULL THEN 1 ELSE 0 END) as ctg_nivdep_null,
  sum(CASE WHEN cs.niv_dep = 'Mantida' THEN 1 ELSE 0 END) as ctg_nivdep_mantida,
  sum(CASE WHEN cs.niv_dep = 'Individual' THEN 1 ELSE 0 END) as ctg_nivdep_individual,
  (sum(CASE WHEN cs.niv_dep IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_nivdep_null,
  (sum(CASE WHEN cs.niv_dep = 'Mantida' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_nivdep_mantida,
  (sum(CASE WHEN cs.niv_dep = 'Individual' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_nivdep_individual,   
  sum(CASE WHEN cs.esfera_a IS NULL THEN 1 ELSE 0 END) as ctg_esfera_a_null,
  sum(CASE WHEN cs.esfera_a = 'Federal' THEN 1 ELSE 0 END) as ctg_esfera_a_federal,
  sum(CASE WHEN cs.esfera_a = 'Municipal' THEN 1 ELSE 0 END) as ctg_esfera_a_municipal,
  sum(CASE WHEN cs.esfera_a = 'Estadual' THEN 1 ELSE 0 END) as ctg_esfera_a_estadual,
  sum(CASE WHEN cs.esfera_a = 'Privada' THEN 1 ELSE 0 END) as ctg_esfera_a_privada,
  (sum(CASE WHEN cs.esfera_a IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_esfera_a_null,
  (sum(CASE WHEN cs.esfera_a = 'Federal' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_esfera_a_federal,
  (sum(CASE WHEN cs.esfera_a = 'Municipal' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_esfera_a_municipal,
  (sum(CASE WHEN cs.esfera_a = 'Estadual' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_esfera_a_estadual,
  (sum(CASE WHEN cs.esfera_a = 'Privada' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_esfera_a_privada,  
  sum(CASE WHEN cs.retencao IS NULL THEN 1 ELSE 0 END) as ctg_retencao_null,
  sum(CASE WHEN cs.retencao = 'Estabelecimento PRIVADO LUCRATIVA' THEN 1 ELSE 0 END) as ctg_retencao_privado_lucrativo,
  sum(CASE WHEN cs.retencao = 'Estabelecimento PUBLICO' THEN 1 ELSE 0 END) as ctg_retencao_publio,
  sum(CASE WHEN cs.retencao = 'Estabelecimento SEM FINS LUCRATIVOS' THEN 1 ELSE 0 END) as ctg_retencao_sem_fins_lucrativos,
  sum(CASE WHEN cs.retencao = 'Estabelecimento SINDICAL' THEN 1 ELSE 0 END) as ctg_retencao_sindical,
  sum(CASE WHEN cs.retencao = 'Estabelecimento PRIVADO LUCRATIVA SIMPLES' THEN 1 ELSE 0 END) as ctg_retencao_privado_lucrativa_simples,
  sum(CASE WHEN cs.retencao = 'Estabelecimento FILANTROPICO' THEN 1 ELSE 0 END) as ctg_retencao_filantropico,
  sum(CASE WHEN cs.retencao = 'Estabelecimento PESSOA FISICA' THEN 1 ELSE 0 END) as ctg_retencao_pessoa_fisica,
  (sum(CASE WHEN cs.retencao IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_retencao_null,
  (sum(CASE WHEN cs.retencao = 'Estabelecimento PRIVADO LUCRATIVA' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_retencao_privado_lucrativo,
  (sum(CASE WHEN cs.retencao = 'Estabelecimento PUBLICO' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_retencao_publio,
  (sum(CASE WHEN cs.retencao = 'Estabelecimento SEM FINS LUCRATIVOS' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_retencao_sem_fins_lucrativos,
  (sum(CASE WHEN cs.retencao = 'Estabelecimento SINDICAL' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_retencao_sindical,
  (sum(CASE WHEN cs.retencao = 'Estabelecimento PRIVADO LUCRATIVA SIMPLES' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_retencao_privado_lucrativa_simples,
  (sum(CASE WHEN cs.retencao = 'Estabelecimento FILANTROPICO' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_retencao_filantropico,
  (sum(CASE WHEN cs.retencao = 'Estabelecimento PESSOA FISICA' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_retencao_pessoa_fisica,  
  sum(CASE WHEN cs.atividad IS NULL THEN 1 ELSE 0 END) as ctg_atividad_null,
  sum(CASE WHEN cs.atividad = 'Unidade SEM atividade de Ensino' THEN 1 ELSE 0 END) as ctg_atividad_sem_atividade,
  sum(CASE WHEN cs.atividad = 'Unidade Escola Superior Isolada' THEN 1 ELSE 0 END) as ctg_atividad_superior_isolada,
  sum(CASE WHEN cs.atividad = 'Unidade Universitária' THEN 1 ELSE 0 END) as ctg_atividad_universitaria,
  sum(CASE WHEN cs.atividad = 'Hospital de Ensino' THEN 1 ELSE 0 END) as ctg_atividad_hospital_ensino,
  sum(CASE WHEN cs.atividad = 'Unidade Auxiliar de Ensino' THEN 1 ELSE 0 END) as ctg_atividad_auxiliar_ensino,
  (sum(CASE WHEN cs.atividad IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_atividad_null,
  (sum(CASE WHEN cs.atividad = 'Unidade SEM atividade de Ensino' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_atividad_sem_atividade,
  (sum(CASE WHEN cs.atividad = 'Unidade Escola Superior Isolada' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_atividad_superior_isolada,
  (sum(CASE WHEN cs.atividad = 'Unidade Universitária' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_atividad_universitaria,
  (sum(CASE WHEN cs.atividad = 'Hospital de Ensino' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_atividad_hospital_ensino,
  (sum(CASE WHEN cs.atividad = 'Unidade Auxiliar de Ensino' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_atividad_auxiliar_ensino,
  sum(CASE WHEN cs.natureza IS NULL THEN 1 ELSE 0 END) as ctg_natureza_null,
  sum(CASE WHEN cs.natureza = 'Adm Direta outros orgãos (MEX, MEx, Marinha,...)' THEN 1 ELSE 0 END) as ctg_natureza_adm_direta_outros_org,
  sum(CASE WHEN cs.natureza = 'Economia Mista' THEN 1 ELSE 0 END) as ctg_natureza_economia_mista,
  sum(CASE WHEN cs.natureza = 'Adm Indireta - Fundação Pública' THEN 1 ELSE 0 END) as ctg_natureza_adm_indireta_fundacao_publica,
  sum(CASE WHEN cs.natureza = 'Serviço Social Autônomo' THEN 1 ELSE 0 END) as ctg_natureza_servico_social_automono,
  sum(CASE WHEN cs.natureza = 'Empresa Privada' THEN 1 ELSE 0 END) as ctg_natureza_empresa_privada,
  sum(CASE WHEN cs.natureza = 'Adm Indireta - Autarquias' THEN 1 ELSE 0 END) as ctg_natureza_adm_indireta_autarquias,
  sum(CASE WHEN cs.natureza = 'Entidade Beneficente SEM fins lucrativos' THEN 1 ELSE 0 END) as ctg_natureza_entidade_beneficente_sem_fins_lucrativos,
  sum(CASE WHEN cs.natureza = 'Administração Direta da Saúde (MS, SES, e SMS)' THEN 1 ELSE 0 END) as ctg_natureza_adm_direta_saude,
  (sum(CASE WHEN cs.natureza IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_natureza_null,
  (sum(CASE WHEN cs.natureza = 'Adm Direta outros orgãos (MEX, MEx, Marinha,...' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_natureza_adm_direta_outros_org,
  (sum(CASE WHEN cs.natureza = 'Economia Mista' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_natureza_economia_mista,
  (sum(CASE WHEN cs.natureza = 'Adm Indireta - Fundação Pública' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_natureza_adm_indireta_fundacao_publica,
  (sum(CASE WHEN cs.natureza = 'Serviço Social Autônomo' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_natureza_servico_social_automono,
  (sum(CASE WHEN cs.natureza = 'Empresa Privada' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_natureza_empresa_privada,
  (sum(CASE WHEN cs.natureza = 'Adm Indireta - Autarquias' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_natureza_adm_indireta_autarquias,
  (sum(CASE WHEN cs.natureza = 'Entidade Beneficente SEM fins lucrativos' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_natureza_entidade_beneficente_sem_fins_lucrativos,
  (sum(CASE WHEN cs.natureza = 'Administração Direta da Saúde (MS, SES, e SMS)' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_natureza_adm_direta_saude,
  sum(CASE WHEN cs.clientel IS NULL THEN 1 ELSE 0 END) as ctg_clientel_null,
  sum(CASE WHEN cs.clientel = 'Atendimento de demanda espontânea e referenciada' THEN 1 ELSE 0 END) as ctg_clientel_demanda_espontanea_referenciada,
  sum(CASE WHEN cs.clientel = 'Atendimento de demanda referenciada' THEN 1 ELSE 0 END) as ctg_clientel_demanda_referenciada,
  sum(CASE WHEN cs.clientel = 'Atendimento de demanda espontânea' THEN 1 ELSE 0 END) as ctg_clientel_demanda_espontanea,
  (sum(CASE WHEN cs.clientel IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_clientel_null,
  (sum(CASE WHEN cs.clientel = 'Atendimento de demanda espontânea e referenciada' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_clientel_demanda_espontanea_referenciada,
  (sum(CASE WHEN cs.clientel = 'Atendimento de demanda referenciada' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_clientel_demanda_referenciada,
  (sum(CASE WHEN cs.clientel = 'Atendimento de demanda espontânea' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_clientel_demanda_espontanea,
  sum(CASE WHEN cs.turno_at IS NULL THEN 1 ELSE 0 END) as ctg_turno_at_null,
  sum(CASE WHEN cs.turno_at = 'ATENDIMENTO TURNOS INTERMITENTES' THEN 1 ELSE 0 END) as ctg_turno_at_turnos_intermitentes,
  sum(CASE WHEN cs.turno_at = 'ATENDIMENTO TURNOS MANHÃ/TARDE' THEN 1 ELSE 0 END) as ctg_turno_at_turnos_manha_tarde,
  sum(CASE WHEN cs.turno_at = 'ATENDIMENTO SOMENTE À NOITE' THEN 1 ELSE 0 END) as ctg_turno_at_somente_noite,
  sum(CASE WHEN cs.turno_at = 'ATENDIMENTO TURNOS MANHÃ/TARDE/NOITE' THEN 1 ELSE 0 END) as ctg_turno_at_turnos_manha_tarde_noite,
  sum(CASE WHEN cs.turno_at = 'ATENDIMENTO SOMENTE À TARDE' THEN 1 ELSE 0 END) as ctg_turno_at_somente_tarde,
  sum(CASE WHEN cs.turno_at = 'ATENDIMENTO CONTÍNUO 24 HORAS/DIA (Pl Sab Dom Fer)' THEN 1 ELSE 0 END) as ctg_turno_at_continuo_24h,
  sum(CASE WHEN cs.turno_at = 'ATENDIMENTO SOMENTE PELA MANHÃ' THEN 1 ELSE 0 END) as ctg_turno_at_somente_manha,
  (sum(CASE WHEN cs.turno_at IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_turno_at_null,
  (sum(CASE WHEN cs.turno_at = 'ATENDIMENTO TURNOS INTERMITENTES' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_turno_at_turnos_intermitentes,
  (sum(CASE WHEN cs.turno_at = 'ATENDIMENTO TURNOS MANHÃ/TARDE' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_turno_at_turnos_manha_tarde,
  (sum(CASE WHEN cs.turno_at = 'ATENDIMENTO SOMENTE À NOITE' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_turno_at_somente_noite,
  (sum(CASE WHEN cs.turno_at = 'ATENDIMENTO TURNOS MANHÃ/TARDE/NOITE' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_turno_at_turnos_manha_tarde_noite,
  (sum(CASE WHEN cs.turno_at = 'ATENDIMENTO SOMENTE À TARDE' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_turno_at_somente_tarde,
  (sum(CASE WHEN cs.turno_at = 'ATENDIMENTO CONTÍNUO 24 HORAS/DIA (Pl Sab Dom Fer)' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_turno_at_continuo_24h,
  (sum(CASE WHEN cs.turno_at = 'ATENDIMENTO SOMENTE PELA MANHÃ' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_turno_at_somente_manha,
  sum(CASE WHEN cs.niv_hier IS NULL THEN 1 ELSE 0 END) as ctg_niv_hier_null,
  sum(CASE WHEN cs.niv_hier = 'NH 7-Média M3' THEN 1 ELSE 0 END) as ctg_niv_hier_nh7_media_m3,
  sum(CASE WHEN cs.niv_hier = 'NH 2-Média M1' THEN 1 ELSE 0 END) as ctg_niv_hier_nh2_media_m1,
  sum(CASE WHEN cs.niv_hier = 'NH 3-Média M2 e M3' THEN 1 ELSE 0 END) as ctg_niv_hier_nh3_media_m2_m3,
  sum(CASE WHEN cs.niv_hier = 'NH 4-AltaComplex.Ambul.' THEN 1 ELSE 0 END) as ctg_niv_hier_nh4_alta_complex_ambul,
  sum(CASE WHEN cs.niv_hier = 'NH 8-AltaCompl.Hos/Amb.' THEN 1 ELSE 0 END) as ctg_niv_hier_nh8_alta_compl_hos_amb,
  sum(CASE WHEN cs.niv_hier = 'NH 5-Baixa M1 e M2' THEN 1 ELSE 0 END) as ctg_niv_hier_nh5_baixa_m1_m2,
  sum(CASE WHEN cs.niv_hier = 'NH 6-Média M2 e M3' THEN 1 ELSE 0 END) as ctg_niv_hier_nh6_media_m2_m3,
  sum(CASE WHEN cs.niv_hier = 'NH 1-PAB-PABA' THEN 1 ELSE 0 END) as ctg_niv_hier_nh1_pab_paba,
  (sum(CASE WHEN cs.niv_hier IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_niv_hier_null,
  (sum(CASE WHEN cs.niv_hier = 'NH 7-Média M3' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_niv_hier_nh7_media_m3,
  (sum(CASE WHEN cs.niv_hier = 'NH 2-Média M1' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_niv_hier_nh2_media_m1,
  (sum(CASE WHEN cs.niv_hier = 'NH 3-Média M2 e M3' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_niv_hier_nh3_media_m2_m3,
  (sum(CASE WHEN cs.niv_hier = 'NH 4-AltaComplex.Ambul.' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_niv_hier_nh4_alta_complex_ambul,
  (sum(CASE WHEN cs.niv_hier = 'NH 8-AltaCompl.Hos/Amb.' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_niv_hier_nh8_alta_compl_hos_amb,
  (sum(CASE WHEN cs.niv_hier = 'NH 5-Baixa M1 e M2' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_niv_hier_nh5_baixa_m1_m2,
  (sum(CASE WHEN cs.niv_hier = 'NH 6-Média M2 e M3' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_niv_hier_nh6_media_m2_m3,
  (sum(CASE WHEN cs.niv_hier = 'NH 1-PAB-PABA' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_niv_hier_nh1_pab_paba,
  sum(CASE WHEN cs.tp_prest IS NULL THEN 1 ELSE 0 END) as ctg_tp_prest_null,
  sum(CASE WHEN cs.tp_prest = 'PUBLICO ESTADUAL' THEN 1 ELSE 0 END) as ctg_tp_prest_publico_estadual,
  sum(CASE WHEN cs.tp_prest = 'SINDICATO' THEN 1 ELSE 0 END) as ctg_tp_prest_sindicato,
  sum(CASE WHEN cs.tp_prest = 'PUBLICO FEDERAL' THEN 1 ELSE 0 END) as ctg_tp_prest_publico_federal,
  sum(CASE WHEN cs.tp_prest = 'TIPO DE PRESTADOR NÃO INFORMADO' THEN 1 ELSE 0 END) as ctg_tp_prest_tipo_nao_informado,
  sum(CASE WHEN cs.tp_prest = 'FILANTROPICO COM CNAS VALIDO' THEN 1 ELSE 0 END) as ctg_tp_prest_filantropico_cnas_valido,
  sum(CASE WHEN cs.tp_prest = 'PRIVADO OPTANTE PELO SIMPLES' THEN 1 ELSE 0 END) as ctg_tp_prest_privado_optante_simples,
  sum(CASE WHEN cs.tp_prest = 'PRIVADO COM FINS LUCRATIVOS' THEN 1 ELSE 0 END) as ctg_tp_prest_privado_fins_lucrativos,
  sum(CASE WHEN cs.tp_prest = 'PUBLICO MUNICIPAL' THEN 1 ELSE 0 END) as ctg_tp_prest_publico_municipal,
  sum(CASE WHEN cs.tp_prest = 'PRIVADO SEM FINS LUCRATIVOS' THEN 1 ELSE 0 END) as ctg_tp_prest_privado_sem_fins_lucrativos,
  (sum(CASE WHEN cs.tp_prest IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tp_prest_null,
  (sum(CASE WHEN cs.tp_prest = 'PUBLICO ESTADUAL' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tp_prest_publico_estadual,
  (sum(CASE WHEN cs.tp_prest = 'SINDICATO' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tp_prest_sindicato,
  (sum(CASE WHEN cs.tp_prest = 'PUBLICO FEDERAL' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tp_prest_publico_federal,
  (sum(CASE WHEN cs.tp_prest = 'TIPO DE PRESTADOR NÃO INFORMADO' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tp_prest_tipo_nao_informado,
  (sum(CASE WHEN cs.tp_prest = 'FILANTROPICO COM CNAS VALIDO' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tp_prest_filantropico_cnas_valido,
  (sum(CASE WHEN cs.tp_prest = 'PRIVADO OPTANTE PELO SIMPLES' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tp_prest_privado_optante_simples,
  (sum(CASE WHEN cs.tp_prest = 'PRIVADO COM FINS LUCRATIVOS' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tp_prest_privado_fins_lucrativos,
  (sum(CASE WHEN cs.tp_prest = 'PUBLICO MUNICIPAL' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tp_prest_publico_municipal,
  (sum(CASE WHEN cs.tp_prest = 'PRIVADO SEM FINS LUCRATIVOS' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tp_prest_privado_sem_fins_lucrativos,
  sum(CASE WHEN cs.tpgestao IS NULL THEN 1 ELSE 0 END) as ctg_tpgestao_null,
  sum(CASE WHEN cs.tpgestao = 'Dupla' THEN 1 ELSE 0 END) as ctg_tpgestao_dupla,
  sum(CASE WHEN cs.tpgestao = 'Municipal' THEN 1 ELSE 0 END) as ctg_tpgestao_municipal,
  sum(CASE WHEN cs.tpgestao = 'Estadual' THEN 1 ELSE 0 END) as ctg_tpgestao_estadual,
  sum(CASE WHEN cs.tpgestao = 'Sem gestão' THEN 1 ELSE 0 END) as ctg_tpgestao_sem_gestao,
  (sum(CASE WHEN cs.tpgestao IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tpgestao_null,
  (sum(CASE WHEN cs.tpgestao = 'Dupla' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tpgestao_dupla,
  (sum(CASE WHEN cs.tpgestao = 'Municipal' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tpgestao_municipal,
  (sum(CASE WHEN cs.tpgestao = 'Estadual' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tpgestao_estadual,
  (sum(CASE WHEN cs.tpgestao = 'Sem gestão' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_tpgestao_sem_gestao,
  sum(CASE WHEN cs.av_acred IS NULL THEN 1 ELSE 0 END) as ctg_av_acred_null,
  sum(CASE WHEN cs.av_acred = 'Sim' THEN 1 ELSE 0 END) as ctg_av_acred_sim,
  sum(CASE WHEN cs.av_acred = 'Não' THEN 1 ELSE 0 END) as ctg_av_acred_nao,
  (sum(CASE WHEN cs.av_acred IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_av_acred_null,
  (sum(CASE WHEN cs.av_acred = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_av_acred_sim,
  (sum(CASE WHEN cs.av_acred = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_av_acred_nao,
  sum(CASE WHEN cs.orgexped IS NULL THEN 1 ELSE 0 END) as ctg_orgexped_null,
  sum(CASE WHEN cs.orgexped = 'SES' THEN 1 ELSE 0 END) as ctg_orgexped_ses,
  sum(CASE WHEN cs.orgexped = 'SMS' THEN 1 ELSE 0 END) as ctg_orgexped_sms,
  (sum(CASE WHEN cs.orgexped IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_orgexped_null,
  (sum(CASE WHEN cs.orgexped = 'SES' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_orgexped_ses,
  (sum(CASE WHEN cs.orgexped = 'SMS' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_orgexped_sms,
  sum(CASE WHEN cs.av_pnass IS NULL THEN 1 ELSE 0 END) as ctg_av_pnass_null,
  sum(CASE WHEN cs.av_pnass = 'Sim' THEN 1 ELSE 0 END) as ctg_av_pnass_sim,
  sum(CASE WHEN cs.av_pnass = 'Não' THEN 1 ELSE 0 END) as ctg_av_pnass_nao,
  (sum(CASE WHEN cs.av_pnass IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_av_pnass_null,
  (sum(CASE WHEN cs.av_pnass = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_av_pnass_sim,
  (sum(CASE WHEN cs.av_pnass = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_av_pnass_nao,
  sum(CASE WHEN cs.gesprg1e IS NULL THEN 1 ELSE 0 END) as ctg_gesprg1e_null,
sum(CASE WHEN cs.gesprg1e = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg1e_sim,
sum(CASE WHEN cs.gesprg1e = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg1e_nao,
(sum(CASE WHEN cs.gesprg1e IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg1e_null,
(sum(CASE WHEN cs.gesprg1e = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg1e_sim,
(sum(CASE WHEN cs.gesprg1e = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg1e_nao,
sum(CASE WHEN cs.gesprg1m IS NULL THEN 1 ELSE 0 END) as ctg_gesprg1m_null,
sum(CASE WHEN cs.gesprg1m = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg1m_sim,
sum(CASE WHEN cs.gesprg1m = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg1m_nao,
(sum(CASE WHEN cs.gesprg1m IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg1m_null,
(sum(CASE WHEN cs.gesprg1m = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg1m_sim,
(sum(CASE WHEN cs.gesprg1m = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg1m_nao,
sum(CASE WHEN cs.gesprg2e IS NULL THEN 1 ELSE 0 END) as ctg_gesprg2e_null,
sum(CASE WHEN cs.gesprg2e = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg2e_sim,
sum(CASE WHEN cs.gesprg2e = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg2e_nao,
(sum(CASE WHEN cs.gesprg2e IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg2e_null,
(sum(CASE WHEN cs.gesprg2e = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg2e_sim,
(sum(CASE WHEN cs.gesprg2e = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg2e_nao,
sum(CASE WHEN cs.gesprg2m IS NULL THEN 1 ELSE 0 END) as ctg_gesprg2m_null,
sum(CASE WHEN cs.gesprg2m = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg2m_sim,
sum(CASE WHEN cs.gesprg2m = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg2m_nao,
(sum(CASE WHEN cs.gesprg2m IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg2m_null,
(sum(CASE WHEN cs.gesprg2m = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg2m_sim,
(sum(CASE WHEN cs.gesprg2m = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg2m_nao,
sum(CASE WHEN cs.gesprg4e IS NULL THEN 1 ELSE 0 END) as ctg_gesprg4e_null,
sum(CASE WHEN cs.gesprg4e = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg4e_sim,
sum(CASE WHEN cs.gesprg4e = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg4e_nao,
(sum(CASE WHEN cs.gesprg4e IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg4e_null,
(sum(CASE WHEN cs.gesprg4e = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg4e_sim,
(sum(CASE WHEN cs.gesprg4e = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg4e_nao,
sum(CASE WHEN cs.gesprg4m IS NULL THEN 1 ELSE 0 END) as ctg_gesprg4m_null,
sum(CASE WHEN cs.gesprg4m = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg4m_sim,
sum(CASE WHEN cs.gesprg4m = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg4m_nao,
(sum(CASE WHEN cs.gesprg4m IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg4m_null,
(sum(CASE WHEN cs.gesprg4m = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg4m_sim,
(sum(CASE WHEN cs.gesprg4m = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg4m_nao,
sum(CASE WHEN cs.nivate_a IS NULL THEN 1 ELSE 0 END) as ctg_nivate_a_null,
sum(CASE WHEN cs.nivate_a = 'Sim' THEN 1 ELSE 0 END) as ctg_nivate_a_sim,
sum(CASE WHEN cs.nivate_a = 'Não' THEN 1 ELSE 0 END) as ctg_nivate_a_nao,
(sum(CASE WHEN cs.nivate_a IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_nivate_a_null,
(sum(CASE WHEN cs.nivate_a = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_nivate_a_sim,
(sum(CASE WHEN cs.nivate_a = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_nivate_a_nao,
sum(CASE WHEN cs.gesprg3e IS NULL THEN 1 ELSE 0 END) as ctg_gesprg3e_null,
sum(CASE WHEN cs.gesprg3e = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg3e_sim,
sum(CASE WHEN cs.gesprg3e = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg3e_nao,
(sum(CASE WHEN cs.gesprg3e IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg3e_null,
(sum(CASE WHEN cs.gesprg3e = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg3e_sim,
(sum(CASE WHEN cs.gesprg3e = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg3e_nao,
sum(CASE WHEN cs.gesprg3m IS NULL THEN 1 ELSE 0 END) as ctg_gesprg3m_null,
sum(CASE WHEN cs.gesprg3m = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg3m_sim,
sum(CASE WHEN cs.gesprg3m = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg3m_nao,
(sum(CASE WHEN cs.gesprg3m IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg3m_null,
(sum(CASE WHEN cs.gesprg3m = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg3m_sim,
(sum(CASE WHEN cs.gesprg3m = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg3m_nao,
sum(CASE WHEN cs.gesprg5e IS NULL THEN 1 ELSE 0 END) as ctg_gesprg5e_null,
sum(CASE WHEN cs.gesprg5e = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg5e_sim,
sum(CASE WHEN cs.gesprg5e = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg5e_nao,
(sum(CASE WHEN cs.gesprg5e IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg5e_null,
(sum(CASE WHEN cs.gesprg5e = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg5e_sim,
(sum(CASE WHEN cs.gesprg5e = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg5e_nao,
sum(CASE WHEN cs.gesprg5m IS NULL THEN 1 ELSE 0 END) as ctg_gesprg5m_null,
sum(CASE WHEN cs.gesprg5m = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg5m_sim,
sum(CASE WHEN cs.gesprg5m = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg5m_nao,
(sum(CASE WHEN cs.gesprg5m IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg5m_null,
(sum(CASE WHEN cs.gesprg5m = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg5m_sim,
(sum(CASE WHEN cs.gesprg5m = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg5m_nao,
sum(CASE WHEN cs.gesprg6e IS NULL THEN 1 ELSE 0 END) as ctg_gesprg6e_null,
sum(CASE WHEN cs.gesprg6e = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg6e_sim,
sum(CASE WHEN cs.gesprg6e = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg6e_nao,
(sum(CASE WHEN cs.gesprg6e IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg6e_null,
(sum(CASE WHEN cs.gesprg6e = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg6e_sim,
(sum(CASE WHEN cs.gesprg6e = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg6e_nao,
sum(CASE WHEN cs.gesprg6m IS NULL THEN 1 ELSE 0 END) as ctg_gesprg6m_null,
sum(CASE WHEN cs.gesprg6m = 'Sim' THEN 1 ELSE 0 END) as ctg_gesprg6m_sim,
sum(CASE WHEN cs.gesprg6m = 'Não' THEN 1 ELSE 0 END) as ctg_gesprg6m_nao,
(sum(CASE WHEN cs.gesprg6m IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg6m_null,
(sum(CASE WHEN cs.gesprg6m = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg6m_sim,
(sum(CASE WHEN cs.gesprg6m = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_gesprg6m_nao,
sum(CASE WHEN cs.nivate_h IS NULL THEN 1 ELSE 0 END) as ctg_nivate_h_null,
sum(CASE WHEN cs.nivate_h = 'Sim' THEN 1 ELSE 0 END) as ctg_nivate_h_sim,
sum(CASE WHEN cs.nivate_h = 'Não' THEN 1 ELSE 0 END) as ctg_nivate_h_nao,
(sum(CASE WHEN cs.nivate_h IS NULL THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_nivate_h_null,
(sum(CASE WHEN cs.nivate_h = 'Sim' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_nivate_h_sim,
(sum(CASE WHEN cs.nivate_h = 'Não' THEN 1 ELSE 0 END)::numeric/count(cs.cnes_st_id))*100 as pct_nivate_h_nao,
sum(CASE WHEN cs.qtleitp1 IS NULL THEN 1 ELSE 0 END) as ctg_qtleitp1_null,
AVG(CASE WHEN cs.qtleitp1 IS NULL THEN 1 ELSE 0 END) as media_qtleitp1_null,
AVG(cs.qtleitp1) AS media_qtleitp1,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleitp1) AS mediana_qtleitp1,
STDDEV(cs.qtleitp1) AS dp_qtleitp1,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleitp1) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleitp1) AS iiq_qtleitp1,
MAX(cs.qtleitp1) AS max_qtleitp1,
MIN(cs.qtleitp1) AS min_qtleitp1,
sum(CASE WHEN cs.qtleitp2 IS NULL THEN 1 ELSE 0 END) as ctg_qtleitp2_null,
AVG(CASE WHEN cs.qtleitp2 IS NULL THEN 1 ELSE 0 END) as media_qtleitp2_null,
AVG(cs.qtleitp2) AS media_qtleitp2,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleitp2) AS mediana_qtleitp2,
STDDEV(cs.qtleitp2) AS dp_qtleitp2,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleitp2) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleitp2) AS iiq_qtleitp2,
MAX(cs.qtleitp2) AS max_qtleitp2,
MIN(cs.qtleitp2) AS min_qtleitp2,
sum(CASE WHEN cs.qtleitp3 IS NULL THEN 1 ELSE 0 END) as ctg_qtleitp3_null,
AVG(CASE WHEN cs.qtleitp3 IS NULL THEN 1 ELSE 0 END) as media_qtleitp3_null,
AVG(cs.qtleitp3) AS media_qtleitp3,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleitp3) AS mediana_qtleitp3,
STDDEV(cs.qtleitp3) AS dp_qtleitp3,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleitp3) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleitp3) AS iiq_qtleitp3,
MAX(cs.qtleitp3) AS max_qtleitp3,
MIN(cs.qtleitp3) AS min_qtleitp3,
sum(CASE WHEN cs.qtinst01 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst01_null,
AVG(CASE WHEN cs.qtinst01 IS NULL THEN 1 ELSE 0 END) as media_qtinst01_null,
AVG(cs.qtinst01) AS media_qtinst01,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst01) AS mediana_qtinst01,
STDDEV(cs.qtinst01) AS dp_qtinst01,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst01) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst01) AS iiq_qtinst01,
MAX(cs.qtinst01) AS max_qtinst01,
MIN(cs.qtinst01) AS min_qtinst01,
sum(CASE WHEN cs.qtinst02 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst02_null,
AVG(CASE WHEN cs.qtinst02 IS NULL THEN 1 ELSE 0 END) as media_qtinst02_null,
AVG(cs.qtinst02) AS media_qtinst02,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst02) AS mediana_qtinst02,
STDDEV(cs.qtinst02) AS dp_qtinst02,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst02) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst02) AS iiq_qtinst02,
MAX(cs.qtinst02) AS max_qtinst02,
MIN(cs.qtinst02) AS min_qtinst02,
sum(CASE WHEN cs.qtinst03 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst03_null,
AVG(CASE WHEN cs.qtinst03 IS NULL THEN 1 ELSE 0 END) as media_qtinst03_null,
AVG(cs.qtinst03) AS media_qtinst03,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst03) AS mediana_qtinst03,
STDDEV(cs.qtinst03) AS dp_qtinst03,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst03) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst03) AS iiq_qtinst03,
MAX(cs.qtinst03) AS max_qtinst03,
MIN(cs.qtinst03) AS min_qtinst03,
sum(CASE WHEN cs.qtinst04 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst04_null,
AVG(CASE WHEN cs.qtinst04 IS NULL THEN 1 ELSE 0 END) as media_qtinst04_null,
AVG(cs.qtinst04) AS media_qtinst04,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst04) AS mediana_qtinst04,
STDDEV(cs.qtinst04) AS dp_qtinst04,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst04) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst04) AS iiq_qtinst04,
MAX(cs.qtinst04) AS max_qtinst04,
MIN(cs.qtinst04) AS min_qtinst04,
sum(CASE WHEN cs.qtinst05 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst05_null,
AVG(CASE WHEN cs.qtinst05 IS NULL THEN 1 ELSE 0 END) as media_qtinst05_null,
AVG(cs.qtinst05) AS media_qtinst05,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst05) AS mediana_qtinst05,
STDDEV(cs.qtinst05) AS dp_qtinst05,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst05) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst05) AS iiq_qtinst05,
MAX(cs.qtinst05) AS max_qtinst05,
MIN(cs.qtinst05) AS min_qtinst05,
sum(CASE WHEN cs.qtinst06 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst06_null,
AVG(CASE WHEN cs.qtinst06 IS NULL THEN 1 ELSE 0 END) as media_qtinst06_null,
AVG(cs.qtinst06) AS media_qtinst06,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst06) AS mediana_qtinst06,
STDDEV(cs.qtinst06) AS dp_qtinst06,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst06) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst06) AS iiq_qtinst06,
MAX(cs.qtinst06) AS max_qtinst06,
MIN(cs.qtinst06) AS min_qtinst06,
sum(CASE WHEN cs.qtinst07 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst07_null,
AVG(CASE WHEN cs.qtinst07 IS NULL THEN 1 ELSE 0 END) as media_qtinst07_null,
AVG(cs.qtinst07) AS media_qtinst07,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst07) AS mediana_qtinst07,
STDDEV(cs.qtinst07) AS dp_qtinst07,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst07) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst07) AS iiq_qtinst07,
MAX(cs.qtinst07) AS max_qtinst07,
MIN(cs.qtinst07) AS min_qtinst07,
sum(CASE WHEN cs.qtinst08 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst08_null,
AVG(CASE WHEN cs.qtinst08 IS NULL THEN 1 ELSE 0 END) as media_qtinst08_null,
AVG(cs.qtinst08) AS media_qtinst08,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst08) AS mediana_qtinst08,
STDDEV(cs.qtinst08) AS dp_qtinst08,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst08) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst08) AS iiq_qtinst08,
MAX(cs.qtinst08) AS max_qtinst08,
MIN(cs.qtinst08) AS min_qtinst08,
sum(CASE WHEN cs.qtinst09 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst09_null,
AVG(CASE WHEN cs.qtinst09 IS NULL THEN 1 ELSE 0 END) as media_qtinst09_null,
AVG(cs.qtinst09) AS media_qtinst09,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst09) AS mediana_qtinst09,
STDDEV(cs.qtinst09) AS dp_qtinst09,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst09) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst09) AS iiq_qtinst09,
MAX(cs.qtinst09) AS max_qtinst09,
MIN(cs.qtinst09) AS min_qtinst09,
sum(CASE WHEN cs.qtinst10 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst10_null,
AVG(CASE WHEN cs.qtinst10 IS NULL THEN 1 ELSE 0 END) as media_qtinst10_null,
AVG(cs.qtinst10) AS media_qtinst10,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst10) AS mediana_qtinst10,
STDDEV(cs.qtinst10) AS dp_qtinst10,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst10) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst10) AS iiq_qtinst10,
MAX(cs.qtinst10) AS max_qtinst10,
MIN(cs.qtinst10) AS min_qtinst10,
sum(CASE WHEN cs.qtinst11 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst11_null,
AVG(CASE WHEN cs.qtinst11 IS NULL THEN 1 ELSE 0 END) as media_qtinst11_null,
AVG(cs.qtinst11) AS media_qtinst11,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst11) AS mediana_qtinst11,
STDDEV(cs.qtinst11) AS dp_qtinst11,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst11) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst11) AS iiq_qtinst11,
MAX(cs.qtinst11) AS max_qtinst11,
MIN(cs.qtinst11) AS min_qtinst11,
sum(CASE WHEN cs.qtinst12 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst12_null,
AVG(CASE WHEN cs.qtinst12 IS NULL THEN 1 ELSE 0 END) as media_qtinst12_null,
AVG(cs.qtinst12) AS media_qtinst12,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst12) AS mediana_qtinst12,
STDDEV(cs.qtinst12) AS dp_qtinst12,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst12) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst12) AS iiq_qtinst12,
MAX(cs.qtinst12) AS max_qtinst12,
MIN(cs.qtinst12) AS min_qtinst12,
sum(CASE WHEN cs.qtinst13 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst13_null,
AVG(CASE WHEN cs.qtinst13 IS NULL THEN 1 ELSE 0 END) as media_qtinst13_null,
AVG(cs.qtinst13) AS media_qtinst13,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst13) AS mediana_qtinst13,
STDDEV(cs.qtinst13) AS dp_qtinst13,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst13) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst13) AS iiq_qtinst13,
MAX(cs.qtinst13) AS max_qtinst13,
MIN(cs.qtinst13) AS min_qtinst13,
sum(CASE WHEN cs.qtinst14 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst14_null,
AVG(CASE WHEN cs.qtinst14 IS NULL THEN 1 ELSE 0 END) as media_qtinst14_null,
AVG(cs.qtinst14) AS media_qtinst14,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst14) AS mediana_qtinst14,
STDDEV(cs.qtinst14) AS dp_qtinst14,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst14) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst14) AS iiq_qtinst14,
MAX(cs.qtinst14) AS max_qtinst14,
MIN(cs.qtinst14) AS min_qtinst14,
sum(CASE WHEN cs.qtinst15 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst15_null,
AVG(CASE WHEN cs.qtinst15 IS NULL THEN 1 ELSE 0 END) as media_qtinst15_null,
AVG(cs.qtinst15) AS media_qtinst15,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst15) AS mediana_qtinst15,
STDDEV(cs.qtinst15) AS dp_qtinst15,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst15) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst15) AS iiq_qtinst15,
MAX(cs.qtinst15) AS max_qtinst15,
MIN(cs.qtinst15) AS min_qtinst15,
sum(CASE WHEN cs.qtinst16 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst16_null,
AVG(CASE WHEN cs.qtinst16 IS NULL THEN 1 ELSE 0 END) as media_qtinst16_null,
AVG(cs.qtinst16) AS media_qtinst16,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst16) AS mediana_qtinst16,
STDDEV(cs.qtinst16) AS dp_qtinst16,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst16) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst16) AS iiq_qtinst16,
MAX(cs.qtinst16) AS max_qtinst16,
MIN(cs.qtinst16) AS min_qtinst16,
sum(CASE WHEN cs.qtinst17 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst17_null,
AVG(CASE WHEN cs.qtinst17 IS NULL THEN 1 ELSE 0 END) as media_qtinst17_null,
AVG(cs.qtinst17) AS media_qtinst17,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst17) AS mediana_qtinst17,
STDDEV(cs.qtinst17) AS dp_qtinst17,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst17) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst17) AS iiq_qtinst17,
MAX(cs.qtinst17) AS max_qtinst17,
MIN(cs.qtinst17) AS min_qtinst17,
sum(CASE WHEN cs.qtinst18 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst18_null,
AVG(CASE WHEN cs.qtinst18 IS NULL THEN 1 ELSE 0 END) as media_qtinst18_null,
AVG(cs.qtinst18) AS media_qtinst18,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst18) AS mediana_qtinst18,
STDDEV(cs.qtinst18) AS dp_qtinst18,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst18) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst18) AS iiq_qtinst18,
MAX(cs.qtinst18) AS max_qtinst18,
MIN(cs.qtinst18) AS min_qtinst18,
sum(CASE WHEN cs.qtinst19 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst19_null,
AVG(CASE WHEN cs.qtinst19 IS NULL THEN 1 ELSE 0 END) as media_qtinst19_null,
AVG(cs.qtinst19) AS media_qtinst19,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst19) AS mediana_qtinst19,
STDDEV(cs.qtinst19) AS dp_qtinst19,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst19) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst19) AS iiq_qtinst19,
MAX(cs.qtinst19) AS max_qtinst19,
MIN(cs.qtinst19) AS min_qtinst19,
sum(CASE WHEN cs.qtinst20 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst20_null,
AVG(CASE WHEN cs.qtinst20 IS NULL THEN 1 ELSE 0 END) as media_qtinst20_null,
AVG(cs.qtinst20) AS media_qtinst20,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst20) AS mediana_qtinst20,
STDDEV(cs.qtinst20) AS dp_qtinst20,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst20) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst20) AS iiq_qtinst20,
MAX(cs.qtinst20) AS max_qtinst20,
MIN(cs.qtinst20) AS min_qtinst20,
sum(CASE WHEN cs.qtinst21 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst21_null,
AVG(CASE WHEN cs.qtinst21 IS NULL THEN 1 ELSE 0 END) as media_qtinst21_null,
AVG(cs.qtinst21) AS media_qtinst21,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst21) AS mediana_qtinst21,
STDDEV(cs.qtinst21) AS dp_qtinst21,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst21) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst21) AS iiq_qtinst21,
MAX(cs.qtinst21) AS max_qtinst21,
MIN(cs.qtinst21) AS min_qtinst21,
sum(CASE WHEN cs.qtinst22 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst22_null,
AVG(CASE WHEN cs.qtinst22 IS NULL THEN 1 ELSE 0 END) as media_qtinst22_null,
AVG(cs.qtinst22) AS media_qtinst22,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst22) AS mediana_qtinst22,
STDDEV(cs.qtinst22) AS dp_qtinst22,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst22) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst22) AS iiq_qtinst22,
MAX(cs.qtinst22) AS max_qtinst22,
MIN(cs.qtinst22) AS min_qtinst22,
sum(CASE WHEN cs.qtinst23 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst23_null,
AVG(CASE WHEN cs.qtinst23 IS NULL THEN 1 ELSE 0 END) as media_qtinst23_null,
AVG(cs.qtinst23) AS media_qtinst23,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst23) AS mediana_qtinst23,
STDDEV(cs.qtinst23) AS dp_qtinst23,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst23) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst23) AS iiq_qtinst23,
MAX(cs.qtinst23) AS max_qtinst23,
MIN(cs.qtinst23) AS min_qtinst23,
sum(CASE WHEN cs.qtinst24 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst24_null,
AVG(CASE WHEN cs.qtinst24 IS NULL THEN 1 ELSE 0 END) as media_qtinst24_null,
AVG(cs.qtinst24) AS media_qtinst24,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst24) AS mediana_qtinst24,
STDDEV(cs.qtinst24) AS dp_qtinst24,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst24) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst24) AS iiq_qtinst24,
MAX(cs.qtinst24) AS max_qtinst24,
MIN(cs.qtinst24) AS min_qtinst24,
sum(CASE WHEN cs.qtinst25 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst25_null,
AVG(CASE WHEN cs.qtinst25 IS NULL THEN 1 ELSE 0 END) as media_qtinst25_null,
AVG(cs.qtinst25) AS media_qtinst25,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst25) AS mediana_qtinst25,
STDDEV(cs.qtinst25) AS dp_qtinst25,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst25) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst25) AS iiq_qtinst25,
MAX(cs.qtinst25) AS max_qtinst25,
MIN(cs.qtinst25) AS min_qtinst25,
sum(CASE WHEN cs.qtinst26 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst26_null,
AVG(CASE WHEN cs.qtinst26 IS NULL THEN 1 ELSE 0 END) as media_qtinst26_null,
AVG(cs.qtinst26) AS media_qtinst26,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst26) AS mediana_qtinst26,
STDDEV(cs.qtinst26) AS dp_qtinst26,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst26) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst26) AS iiq_qtinst26,
MAX(cs.qtinst26) AS max_qtinst26,
MIN(cs.qtinst26) AS min_qtinst26,
sum(CASE WHEN cs.qtinst27 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst27_null,
AVG(CASE WHEN cs.qtinst27 IS NULL THEN 1 ELSE 0 END) as media_qtinst27_null,
AVG(cs.qtinst27) AS media_qtinst27,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst27) AS mediana_qtinst27,
STDDEV(cs.qtinst27) AS dp_qtinst27,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst27) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst27) AS iiq_qtinst27,
MAX(cs.qtinst27) AS max_qtinst27,
MIN(cs.qtinst27) AS min_qtinst27,
sum(CASE WHEN cs.qtinst28 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst28_null,
AVG(CASE WHEN cs.qtinst28 IS NULL THEN 1 ELSE 0 END) as media_qtinst28_null,
AVG(cs.qtinst28) AS media_qtinst28,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst28) AS mediana_qtinst28,
STDDEV(cs.qtinst28) AS dp_qtinst28,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst28) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst28) AS iiq_qtinst28,
MAX(cs.qtinst28) AS max_qtinst28,
MIN(cs.qtinst28) AS min_qtinst28,
sum(CASE WHEN cs.qtinst29 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst29_null,
AVG(CASE WHEN cs.qtinst29 IS NULL THEN 1 ELSE 0 END) as media_qtinst29_null,
AVG(cs.qtinst29) AS media_qtinst29,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst29) AS mediana_qtinst29,
STDDEV(cs.qtinst29) AS dp_qtinst29,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst29) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst29) AS iiq_qtinst29,
MAX(cs.qtinst29) AS max_qtinst29,
MIN(cs.qtinst29) AS min_qtinst29,
sum(CASE WHEN cs.qtinst30 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst30_null,
AVG(CASE WHEN cs.qtinst30 IS NULL THEN 1 ELSE 0 END) as media_qtinst30_null,
AVG(cs.qtinst30) AS media_qtinst30,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst30) AS mediana_qtinst30,
STDDEV(cs.qtinst30) AS dp_qtinst30,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst30) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst30) AS iiq_qtinst30,
MAX(cs.qtinst30) AS max_qtinst30,
MIN(cs.qtinst30) AS min_qtinst30,
sum(CASE WHEN cs.qtinst31 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst31_null,
AVG(CASE WHEN cs.qtinst31 IS NULL THEN 1 ELSE 0 END) as media_qtinst31_null,
AVG(cs.qtinst31) AS media_qtinst31,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst31) AS mediana_qtinst31,
STDDEV(cs.qtinst31) AS dp_qtinst31,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst31) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst31) AS iiq_qtinst31,
MAX(cs.qtinst31) AS max_qtinst31,
MIN(cs.qtinst31) AS min_qtinst31,
sum(CASE WHEN cs.qtinst32 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst32_null,
AVG(CASE WHEN cs.qtinst32 IS NULL THEN 1 ELSE 0 END) as media_qtinst32_null,
AVG(cs.qtinst32) AS media_qtinst32,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst32) AS mediana_qtinst32,
STDDEV(cs.qtinst32) AS dp_qtinst32,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst32) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst32) AS iiq_qtinst32,
MAX(cs.qtinst32) AS max_qtinst32,
MIN(cs.qtinst32) AS min_qtinst32,
sum(CASE WHEN cs.qtinst33 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst33_null,
AVG(CASE WHEN cs.qtinst33 IS NULL THEN 1 ELSE 0 END) as media_qtinst33_null,
AVG(cs.qtinst33) AS media_qtinst33,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst33) AS mediana_qtinst33,
STDDEV(cs.qtinst33) AS dp_qtinst33,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst33) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst33) AS iiq_qtinst33,
MAX(cs.qtinst33) AS max_qtinst33,
MIN(cs.qtinst33) AS min_qtinst33,
sum(CASE WHEN cs.qtinst34 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst34_null,
AVG(CASE WHEN cs.qtinst34 IS NULL THEN 1 ELSE 0 END) as media_qtinst34_null,
AVG(cs.qtinst34) AS media_qtinst34,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst34) AS mediana_qtinst34,
STDDEV(cs.qtinst34) AS dp_qtinst34,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst34) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst34) AS iiq_qtinst34,
MAX(cs.qtinst34) AS max_qtinst34,
MIN(cs.qtinst34) AS min_qtinst34,
sum(CASE WHEN cs.qtinst35 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst35_null,
AVG(CASE WHEN cs.qtinst35 IS NULL THEN 1 ELSE 0 END) as media_qtinst35_null,
AVG(cs.qtinst35) AS media_qtinst35,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst35) AS mediana_qtinst35,
STDDEV(cs.qtinst35) AS dp_qtinst35,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst35) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst35) AS iiq_qtinst35,
MAX(cs.qtinst35) AS max_qtinst35,
MIN(cs.qtinst35) AS min_qtinst35,
sum(CASE WHEN cs.qtinst36 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst36_null,
AVG(CASE WHEN cs.qtinst36 IS NULL THEN 1 ELSE 0 END) as media_qtinst36_null,
AVG(cs.qtinst36) AS media_qtinst36,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst36) AS mediana_qtinst36,
STDDEV(cs.qtinst36) AS dp_qtinst36,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst36) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst36) AS iiq_qtinst36,
MAX(cs.qtinst36) AS max_qtinst36,
MIN(cs.qtinst36) AS min_qtinst36,
sum(CASE WHEN cs.qtinst37 IS NULL THEN 1 ELSE 0 END) as ctg_qtinst37_null,
AVG(CASE WHEN cs.qtinst37 IS NULL THEN 1 ELSE 0 END) as media_qtinst37_null,
AVG(cs.qtinst37) AS media_qtinst37,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtinst37) AS mediana_qtinst37,
STDDEV(cs.qtinst37) AS dp_qtinst37,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtinst37) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtinst37) AS iiq_qtinst37,
MAX(cs.qtinst37) AS max_qtinst37,
MIN(cs.qtinst37) AS min_qtinst37,
sum(CASE WHEN cs.qtleit05 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit05_null,
AVG(CASE WHEN cs.qtleit05 IS NULL THEN 1 ELSE 0 END) as media_qtleit05_null,
AVG(cs.qtleit05) AS media_qtleit05,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit05) AS mediana_qtleit05,
STDDEV(cs.qtleit05) AS dp_qtleit05,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit05) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit05) AS iiq_qtleit05,
MAX(cs.qtleit05) AS max_qtleit05,
MIN(cs.qtleit05) AS min_qtleit05,
sum(CASE WHEN cs.qtleit06 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit06_null,
AVG(CASE WHEN cs.qtleit06 IS NULL THEN 1 ELSE 0 END) as media_qtleit06_null,
AVG(cs.qtleit06) AS media_qtleit06,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit06) AS mediana_qtleit06,
STDDEV(cs.qtleit06) AS dp_qtleit06,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit06) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit06) AS iiq_qtleit06,
MAX(cs.qtleit06) AS max_qtleit06,
MIN(cs.qtleit06) AS min_qtleit06,
sum(CASE WHEN cs.qtleit07 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit07_null,
AVG(CASE WHEN cs.qtleit07 IS NULL THEN 1 ELSE 0 END) as media_qtleit07_null,
AVG(cs.qtleit07) AS media_qtleit07,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit07) AS mediana_qtleit07,
STDDEV(cs.qtleit07) AS dp_qtleit07,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit07) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit07) AS iiq_qtleit07,
MAX(cs.qtleit07) AS max_qtleit07,
MIN(cs.qtleit07) AS min_qtleit07,
sum(CASE WHEN cs.qtleit08 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit08_null,
AVG(CASE WHEN cs.qtleit08 IS NULL THEN 1 ELSE 0 END) as media_qtleit08_null,
AVG(cs.qtleit08) AS media_qtleit08,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit08) AS mediana_qtleit08,
STDDEV(cs.qtleit08) AS dp_qtleit08,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit08) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit08) AS iiq_qtleit08,
MAX(cs.qtleit08) AS max_qtleit08,
MIN(cs.qtleit08) AS min_qtleit08,
sum(CASE WHEN cs.qtleit09 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit09_null,
AVG(CASE WHEN cs.qtleit09 IS NULL THEN 1 ELSE 0 END) as media_qtleit09_null,
AVG(cs.qtleit09) AS media_qtleit09,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit09) AS mediana_qtleit09,
STDDEV(cs.qtleit09) AS dp_qtleit09,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit09) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit09) AS iiq_qtleit09,
MAX(cs.qtleit09) AS max_qtleit09,
MIN(cs.qtleit09) AS min_qtleit09,
sum(CASE WHEN cs.qtleit19 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit19_null,
AVG(CASE WHEN cs.qtleit19 IS NULL THEN 1 ELSE 0 END) as media_qtleit19_null,
AVG(cs.qtleit19) AS media_qtleit19,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit19) AS mediana_qtleit19,
STDDEV(cs.qtleit19) AS dp_qtleit19,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit19) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER by cs.qtleit19) AS iiq_qtleit19,
MAX(cs.qtleit19) AS max_qtleit19,
MIN(cs.qtleit19) AS min_qtleit19,
sum(CASE WHEN cs.qtleit20 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit20_null,
AVG(CASE WHEN cs.qtleit20 IS NULL THEN 1 ELSE 0 END) as media_qtleit20_null,
AVG(cs.qtleit20) AS media_qtleit20,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit20) AS mediana_qtleit20,
STDDEV(cs.qtleit20) AS dp_qtleit20,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit20) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit20) AS iiq_qtleit20,
MAX(cs.qtleit20) AS max_qtleit20,
MIN(cs.qtleit20) AS min_qtleit20,
sum(CASE WHEN cs.qtleit21 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit21_null,
AVG(CASE WHEN cs.qtleit21 IS NULL THEN 1 ELSE 0 END) as media_qtleit21_null,
AVG(cs.qtleit21) AS media_qtleit21,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit21) AS mediana_qtleit21,
STDDEV(cs.qtleit21) AS dp_qtleit21,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit21) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit21) AS iiq_qtleit21,
MAX(cs.qtleit21) AS max_qtleit21,
MIN(cs.qtleit21) AS min_qtleit21,
sum(CASE WHEN cs.qtleit22 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit22_null,
AVG(CASE WHEN cs.qtleit22 IS NULL THEN 1 ELSE 0 END) as media_qtleit22_null,
AVG(cs.qtleit22) AS media_qtleit22,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit22) AS mediana_qtleit22,
STDDEV(cs.qtleit22) AS dp_qtleit22,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit22) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit22) AS iiq_qtleit22,
MAX(cs.qtleit22) AS max_qtleit22,
MIN(cs.qtleit22) AS min_qtleit22,
sum(CASE WHEN cs.qtleit23 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit23_null,
AVG(CASE WHEN cs.qtleit23 IS NULL THEN 1 ELSE 0 END) as media_qtleit23_null,
AVG(cs.qtleit23) AS media_qtleit23,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit23) AS mediana_qtleit23,
STDDEV(cs.qtleit23) AS dp_qtleit23,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit23) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit23) AS iiq_qtleit23,
MAX(cs.qtleit23) AS max_qtleit23,
MIN(cs.qtleit23) AS min_qtleit23,
sum(CASE WHEN cs.qtleit32 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit32_null,
AVG(CASE WHEN cs.qtleit32 IS NULL THEN 1 ELSE 0 END) as media_qtleit32_null,
AVG(cs.qtleit32) AS media_qtleit32,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit32) AS mediana_qtleit32,
STDDEV(cs.qtleit32) AS dp_qtleit32,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit32) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit32) AS iiq_qtleit32,
MAX(cs.qtleit32) AS max_qtleit32,
MIN(cs.qtleit32) AS min_qtleit32,
sum(CASE WHEN cs.qtleit34 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit34_null,
AVG(CASE WHEN cs.qtleit34 IS NULL THEN 1 ELSE 0 END) as media_qtleit34_null,
AVG(cs.qtleit34) AS media_qtleit34,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit34) AS mediana_qtleit34,
STDDEV(cs.qtleit34) AS dp_qtleit34,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit34) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit34) AS iiq_qtleit34,
MAX(cs.qtleit34) AS max_qtleit34,
MIN(cs.qtleit34) AS min_qtleit34,
sum(CASE WHEN cs.qtleit38 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit38_null,
AVG(CASE WHEN cs.qtleit38 IS NULL THEN 1 ELSE 0 END) as media_qtleit38_null,
AVG(cs.qtleit38) AS media_qtleit38,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit38) AS mediana_qtleit38,
STDDEV(cs.qtleit38) AS dp_qtleit38,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit38) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit38) AS iiq_qtleit38,
MAX(cs.qtleit38) AS max_qtleit38,
MIN(cs.qtleit38) AS min_qtleit38,
sum(CASE WHEN cs.qtleit39 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit39_null,
AVG(CASE WHEN cs.qtleit39 IS NULL THEN 1 ELSE 0 END) as media_qtleit39_null,
AVG(cs.qtleit39) AS media_qtleit39,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit39) AS mediana_qtleit39,
STDDEV(cs.qtleit39) AS dp_qtleit39,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit39) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit39) AS iiq_qtleit39,
MAX(cs.qtleit39) AS max_qtleit39,
MIN(cs.qtleit39) AS min_qtleit39,
sum(CASE WHEN cs.qtleit40 IS NULL THEN 1 ELSE 0 END) as ctg_qtleit40_null,
AVG(CASE WHEN cs.qtleit40 IS NULL THEN 1 ELSE 0 END) as media_qtleit40_null,
AVG(cs.qtleit40) AS media_qtleit40,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY cs.qtleit40) AS mediana_qtleit40,
STDDEV(cs.qtleit40) AS dp_qtleit40,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY cs.qtleit40) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY cs.qtleit40) AS iiq_qtleit40,
MAX(cs.qtleit40) AS max_qtleit40,
MIN(cs.qtleit40) AS min_qtleit40
from public.cnes_st cs
group by cs.codufmun,
		 cs.nu_mes,
		 cs.nu_ano;
				



  