drop table agrupado.ibge_pib;

CREATE TABLE agrupado.ibge_pib_agrupado AS

SELECT 
  ip.codigo_municipio as codigo_municipio,
  ip.ano_notificacao as nu_ano,
CASE WHEN ip.tipo_concentracao_urbana IS NULL THEN 1 ELSE 0 END as sum_tipo_concentracao_urbana_null,
CASE WHEN ip.tipo_concentracao_urbana = 'Média concentração urbana' THEN 1 ELSE 0 END as sum_tipo_concentracao_urbana_media,
CASE WHEN ip.tipo_concentracao_urbana = 'Grande concentração urbana' THEN 1 ELSE 0 END as sum_tipo_concentracao_urbana_grande,
CASE WHEN ip.amazonia_legal IS NULL THEN 1 ELSE 0 END as sum_amazonia_legal_null,
CASE WHEN ip.amazonia_legal = 'Sim' THEN 1 ELSE 0 END as sum_amazonia_legal_sim,
CASE WHEN ip.amazonia_legal = 'Não' THEN 1 ELSE 0 END as sum_amazonia_legal_nao,
CASE WHEN ip.semiarido IS NULL THEN 1 ELSE 0 END as sum_semiarido_null,
CASE WHEN ip.semiarido = 'Sim' THEN 1 ELSE 0 END as sum_semiarido_sim,
CASE WHEN ip.semiarido = 'Não' THEN 1 ELSE 0 END as sum_semiarido_nao,
CASE WHEN ip.cidade_regiao_de_sao_paulo IS NULL THEN 1 ELSE 0 END as sum_cidade_regiao_sp_null,
CASE WHEN ip.cidade_regiao_de_sao_paulo = 'Sim' THEN 1 ELSE 0 END as sum_cidade_regiao_sp_sim,
CASE WHEN ip.cidade_regiao_de_sao_paulo = 'Não' THEN 1 ELSE 0 END as sum_cidade_regiao_sp_nao,
CASE WHEN ip.atividade_maior_vab IS NULL THEN 1 ELSE 0 END as sum_atividade_maior_vab_null,
CASE WHEN ip.atividade_maior_vab = 'Agricultura, inclusive apoio à agricultura e a pós colheita' THEN 1 ELSE 0 END as sum_atividade_maior_vab_agricultura,
CASE WHEN ip.atividade_maior_vab = 'Demais serviços' THEN 1 ELSE 0 END as sum_atividade_maior_vab_demais_servicos,
CASE WHEN ip.atividade_maior_vab = 'Construção' THEN 1 ELSE 0 END as sum_atividade_maior_vab_construcao,
CASE WHEN ip.atividade_maior_vab = 'Comércio e reparação de veículos automotores e motocicletas' THEN 1 ELSE 0 END as sum_atividade_maior_vab_comercio_reparacao,
CASE WHEN ip.atividade_maior_vab = 'Eletricidade e gás, água, esgoto, atividades de gestão de resíduos e descontaminação' THEN 1 ELSE 0 END as sum_atividade_maior_vab_eletricidade_gas,
CASE WHEN ip.atividade_maior_vab = 'Produção florestal, pesca e aquicultura' THEN 1 ELSE 0 END as sum_atividade_maior_vab_producao_florestal_pesca,
CASE WHEN ip.atividade_maior_vab = 'Indústrias de transformação' THEN 1 ELSE 0 END as sum_atividade_maior_vab_industrias_transformacao,
CASE WHEN ip.atividade_maior_vab = 'Administração, defesa, educação e saúde públicas e seguridade social' THEN 1 ELSE 0 END as sum_atividade_maior_vab_administracao_defesa,
CASE WHEN ip.atividade_maior_vab = 'Indústrias extrativas' THEN 1 ELSE 0 END as sum_atividade_maior_vab_industrias_extrativas,
CASE WHEN ip.atividade_maior_vab = 'Pecuária, inclusive apoio à pecuária' THEN 1 ELSE 0 END as sum_atividade_maior_vab_pecuaria,
CASE WHEN ip.atividade_seg_maior_vab IS NULL THEN 1 ELSE 0 END as sum_atividade_seg_maior_vab_null,
CASE WHEN ip.atividade_seg_maior_vab = 'Agricultura, inclusive apoio à agricultura e a pós colheita' THEN 1 ELSE 0 END as sum_atividade_seg_maior_vab_agricultura,
CASE WHEN ip.atividade_seg_maior_vab = 'Demais serviços' THEN 1 ELSE 0 END as sum_atividade_seg_maior_vab_demais_servicos,
CASE WHEN ip.atividade_seg_maior_vab = 'Construção' THEN 1 ELSE 0 END as sum_atividade_seg_maior_vab_construcao,
CASE WHEN ip.atividade_seg_maior_vab = 'Comércio e reparação de veículos automotores e motocicletas' THEN 1 ELSE 0 END as sum_atividade_seg_maior_vab_comercio_reparacao,
CASE WHEN ip.atividade_seg_maior_vab = 'Eletricidade e gás, água, esgoto, atividades de gestão de resíduos e descontaminação' THEN 1 ELSE 0 END as sum_atividade_seg_maior_vab_eletricidade_gas,
CASE WHEN ip.atividade_seg_maior_vab = 'Produção florestal, pesca e aquicultura' THEN 1 ELSE 0 END as sum_atividade_seg_maior_vab_producao_florestal_pesca,
CASE WHEN ip.atividade_seg_maior_vab = 'Indústrias de transformação' THEN 1 ELSE 0 END as sum_atividade_seg_maior_vab_industrias_transformacao,
CASE WHEN ip.atividade_seg_maior_vab = 'Administração, defesa, educação e saúde públicas e seguridade social' THEN 1 ELSE 0 END as sum_atividade_seg_maior_vab_administracao_defesa,
CASE WHEN ip.atividade_seg_maior_vab = 'Indústrias extrativas' THEN 1 ELSE 0 END as sum_atividade_seg_maior_vab_industrias_extrativas,
CASE WHEN ip.atividade_seg_maior_vab = 'Pecuária, inclusive apoio à pecuária' THEN 1 ELSE 0 END as sum_atividade_seg_maior_vab_pecuaria,
CASE WHEN ip.atividade_ter_maior_vab IS NULL THEN 1 ELSE 0 END as sum_atividade_ter_maior_vab_null,
CASE WHEN ip.atividade_ter_maior_vab = 'Agricultura, inclusive apoio à agricultura e a pós colheita' THEN 1 ELSE 0 END as sum_atividade_ter_maior_vab_agricultura,
CASE WHEN ip.atividade_ter_maior_vab = 'Demais serviços' THEN 1 ELSE 0 END as sum_atividade_ter_maior_vab_demais_servicos,
CASE WHEN ip.atividade_ter_maior_vab = 'Construção' THEN 1 ELSE 0 END as sum_atividade_ter_maior_vab_construcao,
CASE WHEN ip.atividade_ter_maior_vab = 'Comércio e reparação de veículos automotores e motocicletas' THEN 1 ELSE 0 END as sum_atividade_ter_maior_vab_comercio_reparacao,
CASE WHEN ip.atividade_ter_maior_vab = 'Eletricidade e gás, água, esgoto, atividades de gestão de resíduos e descontaminação' THEN 1 ELSE 0 END as sum_atividade_ter_maior_vab_eletricidade_gas,
CASE WHEN ip.atividade_ter_maior_vab = 'Produção florestal, pesca e aquicultura' THEN 1 ELSE 0 END as sum_atividade_ter_maior_vab_producao_florestal_pesca,
CASE WHEN ip.atividade_ter_maior_vab = 'Indústrias de transformação' THEN 1 ELSE 0 END as sum_atividade_ter_maior_vab_industrias_transformacao,
CASE WHEN ip.atividade_ter_maior_vab = 'Administração, defesa, educação e saúde públicas e seguridade social' THEN 1 ELSE 0 END as sum_atividade_ter_maior_vab_administracao_defesa,
CASE WHEN ip.atividade_ter_maior_vab = 'Indústrias extrativas' THEN 1 ELSE 0 END as sum_atividade_ter_maior_vab_industrias_extrativas,
CASE WHEN ip.atividade_ter_maior_vab = 'Pecuária, inclusive apoio à pecuária' THEN 1 ELSE 0 END as sum_atividade_ter_maior_vab_pecuaria,
  ip.vab_agropecuaria,
  ip.vab_industria,
  ip.vab_servicos,
  ip.vab_adm_publica,
  ip.vab_total,
  ip.impostos,
  ip.pib,
  ip.pib_per_capita
FROM public.ibge_pib ip;
