DROP TABLE IF EXISTS "Ibge_pib";

CREATE TABLE "ibge_pib" (
    "ano_notificacao" VARCHAR(4) NOT NULL,
    "codigo_grande_regiao" INT,
    "nome_grande_regiao" VARCHAR(255),
    "codigo_uf" INT,
    "uf" VARCHAR(255),
    "nome_uf" VARCHAR(255),
    "codigo_municipio_completo" INT,
    "municipio" VARCHAR(255),
    "regiao_metropolitana" VARCHAR(255),
    "codigo_mesorregiao" INT,
    "nome_mesorregiao" VARCHAR(255),
    "codigo_microrregiao" INT,
    "nome_microrregiao" VARCHAR(255),
    "codigo_regiao_imediata" INT,
    "nome_regiao_imediata" VARCHAR(255),
    "municipio_regiao_imediata" VARCHAR(255),
    "codigo_regiao_intermediaria" INT,
    "nome_regiao_intermediaria" VARCHAR(255),
    "municipio_regiao_intermediaria" VARCHAR(255),
    "codigo_concentracao_urbana" INT,
    "nome_concentracao_urbana" VARCHAR(255),
    "tipo_concentracao_urbana" VARCHAR(255),
    "codigo_arranjo_populacional" INT,
    "nome_arranjo_populacional" VARCHAR(255),
    "hierarquia_urbana" VARCHAR(255),
    "hierarquia_urbana_principais_categorias" VARCHAR(255),
    "codigo_regiao_rural" INT,
    "nome_regiao_rural" VARCHAR(255),
    "regiao_rural_classificacao_nucleo" VARCHAR(255),
    "amazonia_legal" VARCHAR(3),
    "semiarido" VARCHAR(3),
    "cidade_regiao_de_sao_paulo" VARCHAR(3),
    "vab_agropecuaria" FLOAT,
    "vab_industria" FLOAT,
    "vab_servicos" FLOAT,
    "vab_adm_publica" FLOAT,
    "vab_total" FLOAT,
    "impostos" FLOAT,
    "pib" FLOAT,
    "pib_per_capita" FLOAT,
    "atividade_maior_vab" VARCHAR(255),
    "atividade_seg_maior_vab" VARCHAR(255),
    "atividade_ter_maior_vab" VARCHAR(255),
    "codigo_municipio" VARCHAR(6) NOT NULL,
    PRIMARY KEY ("ano_notificacao", "codigo_municipio")
);