DROP TABLE IF EXISTS "biomaps";

CREATE TABLE "biomaps" (
    "biomaps_id" SERIAL,
	"id_municip" varchar(6), 
	"biome" varchar(25), 
	"nu_ano" varchar(4), 
	"aquaculture" float, 
	"beach_and_dune" float,
	"citrus" float, 
	"coffe" float, 
	"cotton" float, 
	"flooded_forest" float, 
	"forest_formation" float,
	"forest_plantation" float, 
	"grassland" float, 
	"magrove" float, 
	"mining" float,
	"mosaic_of_agriculture_and_pasture" float, 
	"non_observed" float,
	"other_non_forest_natural_formation" float, 
	"other_non_vegetated_area" float,
	"other_perennial_crops" float, 
	"other_temporary_crops" float, 
	"palm_oil" float, 
	"pasture" float,
	"restinga_herbácea_arbustiva" float, 
	"rice" float, 
	"river_lake_and_ocean" float,
	"rocky_outcrop" float, 
	"salt_flat" float, 
	"savanna_formation" float, 
	"soy_beans" float,
	"sugar_cane" float, 
	"urban_infrastructure" float, 
	"wetland" float, 
	"wooded_restinga" float, 
    PRIMARY KEY ("biomaps_id")
);