

CREATE TABLE agrupado.sim_agrupado AS

with tabela_dia_semana as (
SELECT 
  f.codigo_municipio,
  f.nu_mes,
  f.nu_ano,
  sum(CASE WHEN f.day_of_week = 'Thursday ' THEN 1 ELSE 0 END) as ctg_day_of_week_Thursday,
  sum(CASE WHEN f.day_of_week = 'Wednesday' THEN 1 ELSE 0 END) as ctg_day_of_week_Wednesday,
  sum(CASE WHEN f.day_of_week = 'Saturday ' THEN 1 ELSE 0 END) as ctg_day_of_week_Saturday,
  sum(CASE WHEN f.day_of_week = 'Monday   ' THEN 1 ELSE 0 END) as ctg_day_of_week_Monday,
  sum(CASE WHEN f.day_of_week = 'Friday   ' THEN 1 ELSE 0 END) as ctg_day_of_week_Friday,
  sum(CASE WHEN f.day_of_week = 'Tuesday  ' THEN 1 ELSE 0 END) as ctg_day_of_week_Tuesday,
  sum(CASE WHEN f.day_of_week = 'Sunday' THEN 1 ELSE 0 END) as ctg_day_of_week_Sunday,
  (sum(CASE WHEN f.day_of_week = 'Thursday ' THEN 1 ELSE 0 END)::numeric/count(f.sim_id))*100 as pct_day_of_week_Thursday,
  (sum(CASE WHEN f.day_of_week = 'Wednesday' THEN 1 ELSE 0 END)::numeric/count(f.sim_id))*100 as pct_day_of_week_Wednesday,
  (sum(CASE WHEN f.day_of_week = 'Saturday ' THEN 1 ELSE 0 END)::numeric/count(f.sim_id))*100 as pct_day_of_week_Saturday,
  (sum(CASE WHEN f.day_of_week = 'Monday   ' THEN 1 ELSE 0 END)::numeric/count(f.sim_id))*100 as pct_day_of_week_Monday,
  (sum(CASE WHEN f.day_of_week = 'Friday   ' THEN 1 ELSE 0 END)::numeric/count(f.sim_id))*100 as pct_day_of_week_Friday,
  (sum(CASE WHEN f.day_of_week = 'Tuesday  ' THEN 1 ELSE 0 END)::numeric/count(f.sim_id))*100 as pct_day_of_week_Tuesday,
  (sum(CASE WHEN f.day_of_week = 'Sunday' THEN 1 ELSE 0 END)::numeric/count(f.sim_id))*100 as pct_day_of_week_Sunday
  from (select s.codigo_municipio,
  s.sim_id,
  s.nu_mes,
  s.nu_ano,
  s.dtobito,
  TO_CHAR(s.dtobito, 'Day') AS day_of_week from public.sim s) as f
 GROUP BY f.codigo_municipio, f.nu_mes, f.nu_ano),


restante_tabela as (
SELECT 
  s.codigo_municipio,
  s.nu_mes,
  s.nu_ano,
  count(s.sim_id),
  sum(CASE WHEN s.sexo IS NULL THEN 1 ELSE 0 END) as sum_sexo_null,
  sum(CASE WHEN s.sexo = 'Feminino' THEN 1 ELSE 0 END) as sum_sexo_fem,
  sum(CASE WHEN s.sexo = 'Masculino' THEN 1 ELSE 0 END) as sum_sexo_mas,
  sum(CASE WHEN s.sexo = 'Ignorado' THEN 1 ELSE 0 END) as sum_sexo_ign,
  (sum(CASE WHEN s.sexo IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_sexo_null,
  (sum(CASE WHEN s.sexo = 'Feminino' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_sexo_fem,
  (sum(CASE WHEN s.sexo = 'Masculino' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_sexo_mas,
  (sum(CASE WHEN s.sexo = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_sexo_ign,
  sum(CASE WHEN s.idade_anos IS NULL THEN 1 ELSE 0 END) as ctg_idade_anos_null,
  AVG(CASE WHEN s.idade_anos IS NULL THEN 1 ELSE 0 END) as media_idade_anos_null,
  AVG(idade_anos) AS media_idade_anos,
  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY idade_anos) AS mediana_idade_anos,
  STDDEV(idade_anos) AS dp_idade_anos,
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY idade_anos) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY idade_anos) AS iiq_idade_anos,
  MAX(idade_anos) AS max_idade_anos,
  MIN(idade_anos) AS min_idade_anos,
  sum(CASE WHEN s.racacor IS NULL THEN 1 ELSE 0 END) as ctg_raca_null,
  sum(CASE WHEN s.racacor = 'Preta' THEN 1 ELSE 0 END) as ctg_racacor_Preta,
  sum(CASE WHEN s.racacor = 'Parda' THEN 1 ELSE 0 END) as ctg_racacor_Parda,
  sum(CASE WHEN s.racacor = 'Amarela' THEN 1 ELSE 0 END) as ctg_racacor_Amarela,
  sum(CASE WHEN s.racacor = 'Branca' THEN 1 ELSE 0 END) as ctg_racacor_Branca,
  sum(CASE WHEN s.racacor = 'Indígena' THEN 1 ELSE 0 END) as ctg_racacor_Indigena,
  (sum(CASE WHEN s.racacor IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_raca_null,
  (sum(CASE WHEN s.racacor = 'Preta' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_racacor_Preta,
  (sum(CASE WHEN s.racacor = 'Parda' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_racacor_Parda,
  (sum(CASE WHEN s.racacor = 'Amarela' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_racacor_Amarela,
  (sum(CASE WHEN s.racacor = 'Branca' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_racacor_Branca,
  (sum(CASE WHEN s.racacor = 'Indígena' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_racacor_Indigena,
  sum(CASE WHEN s.estciv IS NULL THEN 1 ELSE 0 END) as ctg_estciv_null,
  sum(CASE WHEN s.estciv = 'Ignorado' THEN 1 ELSE 0 END) as ctg_estciv_Ignorado,
  sum(CASE WHEN s.estciv = 'Viúvo' THEN 1 ELSE 0 END) as ctg_estciv_Viuvo,
  sum(CASE WHEN s.estciv = 'Casado' THEN 1 ELSE 0 END) as ctg_estciv_Casado,
  sum(CASE WHEN s.estciv = 'Separado' THEN 1 ELSE 0 END) as ctg_estciv_Separado,
  sum(CASE WHEN s.estciv = 'União' THEN 1 ELSE 0 END) as ctg_estciv_Uniao,
  sum(CASE WHEN s.estciv = 'Solteiro' THEN 1 ELSE 0 END) as ctg_estciv_Solteiro,
  (sum(CASE WHEN s.estciv IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_estciv_null,
  (sum(CASE WHEN s.estciv = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_estciv_Ignorado,
  (sum(CASE WHEN s.estciv = 'Viúvo' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_estciv_Viuvo,
  (sum(CASE WHEN s.estciv = 'Casado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_estciv_Casado,
  (sum(CASE WHEN s.estciv = 'Separado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_estciv_Separado,
  (sum(CASE WHEN s.estciv = 'União' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_estciv_Uniao,
  (sum(CASE WHEN s.estciv = 'Solteiro' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_estciv_Solteiro,
  sum(CASE WHEN s.esc IS NULL THEN 1 ELSE 0 END) as ctg_esc_null,
  sum(CASE WHEN s.esc = 'De 8 a 11 anos' THEN 1 ELSE 0 END) as ctg_esc_De_8_a_11_anos,
  sum(CASE WHEN s.esc = '12 anos e mais' THEN 1 ELSE 0 END) as ctg_esc_12_anos_e_mais,
  sum(CASE WHEN s.esc = 'Ignorado' THEN 1 ELSE 0 END) as ctg_esc_Ignorado,
  sum(CASE WHEN s.esc = 'De 4 a 7 anos' THEN 1 ELSE 0 END) as ctg_esc_De_4_a_7_anos,
  sum(CASE WHEN s.esc = 'Nenhuma' THEN 1 ELSE 0 END) as ctg_esc_Nenhuma,
  sum(CASE WHEN s.esc = 'De 1 a 3 anos' THEN 1 ELSE 0 END) as ctg_esc_De_1_a_3_anos,
  (sum(CASE WHEN s.esc IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_esc_null,
  (sum(CASE WHEN s.esc = 'De 8 a 11 anos' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_esc_De_8_a_11_anos,
  (sum(CASE WHEN s.esc = '12 anos e mais' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_esc_12_anos_e_mais,
  (sum(CASE WHEN s.esc = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_esc_Ignorado,
  (sum(CASE WHEN s.esc = 'De 4 a 7 anos' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_esc_De_4_a_7_anos,
  (sum(CASE WHEN s.esc = 'Nenhuma' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_esc_Nenhuma,
  (sum(CASE WHEN s.esc = 'De 1 a 3 anos' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_esc_De_1_a_3_anos,
  sum(CASE WHEN s.lococor IS NULL THEN 1 ELSE 0 END) as ctg_lococor_null,
  sum(CASE WHEN s.lococor = 'Hospital' THEN 1 ELSE 0 END) as ctg_lococor_Hospital,
  sum(CASE WHEN s.lococor = 'Ignorado' THEN 1 ELSE 0 END) as ctg_lococor_Ignorado,
  sum(CASE WHEN s.lococor = 'Via pública' THEN 1 ELSE 0 END) as ctg_lococor_Via_publica,
  sum(CASE WHEN s.lococor = 'Domicílio' THEN 1 ELSE 0 END) as ctg_lococor_Domicilio,
  sum(CASE WHEN s.lococor = 'Aldeia indígena' THEN 1 ELSE 0 END) as ctg_lococor_Aldeia_indigena,
  sum(CASE WHEN s.lococor = 'Outros estabelecimentos de saúde' THEN 1 ELSE 0 END) as ctg_lococor_Outros_estabelecimentos_de_saude,
  sum(CASE WHEN s.lococor = 'Outros' THEN 1 ELSE 0 END) as ctg_lococor_Outros,
  (sum(CASE WHEN s.lococor IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_lococor_null,
  (sum(CASE WHEN s.lococor = 'Hospital' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_lococor_Hospital,
  (sum(CASE WHEN s.lococor = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_lococor_Ignorado,
  (sum(CASE WHEN s.lococor = 'Via pública' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_lococor_Via_publica,
  (sum(CASE WHEN s.lococor = 'Domicílio' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_lococor_Domicilio,
  (sum(CASE WHEN s.lococor = 'Aldeia indígena' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_lococor_Aldeia_indigena,
  (sum(CASE WHEN s.lococor = 'Outros estabelecimentos de saúde' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_lococor_Outros_estabelecimentos_de_saude,
  (sum(CASE WHEN s.lococor = 'Outros' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_lococor_Outros,
  sum(CASE WHEN s.idademae IS NULL THEN 1 ELSE 0 END) as ctg_idademae_null,
  AVG(CASE WHEN s.idademae IS NULL THEN 1 ELSE 0 END) as media_idademae_null,
  AVG(idademae) AS media_idademae,
  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY idademae) AS mediana_idademae,
  STDDEV(idademae) AS dp_idademae,
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY idademae) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY idademae) AS iiq_idademae,
  MAX(idademae) AS max_idademae,
  MIN(idademae) AS min_idademae,
  sum(CASE WHEN s.escmae IS NULL THEN 1 ELSE 0 END) as ctg_escmae_null,
  sum(CASE WHEN s.escmae = 'De 8 a 11 anos' THEN 1 ELSE 0 END) as ctg_escmae_De_8_a_11_anos,
  sum(CASE WHEN s.escmae = '12 anos e mais' THEN 1 ELSE 0 END) as ctg_escmae_12_anos_e_mais,
  sum(CASE WHEN s.escmae = 'Ignorado' THEN 1 ELSE 0 END) as ctg_escmae_Ignorado,
  sum(CASE WHEN s.escmae = 'De 4 a 7 anos' THEN 1 ELSE 0 END) as ctg_escmae_De_4_a_7_anos,
  sum(CASE WHEN s.escmae = 'Nenhuma' THEN 1 ELSE 0 END) as ctg_escmae_Nenhuma,
  sum(CASE WHEN s.escmae = 'De 1 a 3 anos' THEN 1 ELSE 0 END) as ctg_escmae_De_1_a_3_anos,
  (sum(CASE WHEN s.escmae IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_escmae_null,
  (sum(CASE WHEN s.escmae = 'De 8 a 11 anos' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_escmae_De_8_a_11_anos,
  (sum(CASE WHEN s.escmae = '12 anos e mais' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_escmae_12_anos_e_mais,
  (sum(CASE WHEN s.escmae = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_escmae_Ignorado,
  (sum(CASE WHEN s.escmae = 'De 4 a 7 anos' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_escmae_De_4_a_7_anos,
  (sum(CASE WHEN s.escmae = 'Nenhuma' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_escmae_Nenhuma,
  (sum(CASE WHEN s.escmae = 'De 1 a 3 anos' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_escmae_De_1_a_3_anos,
  sum(CASE WHEN s.gravidez IS NULL THEN 1 ELSE 0 END) as ctg_gravidez_null,
  sum(CASE WHEN s.gravidez = 'Ignorada' THEN 1 ELSE 0 END) as ctg_gravidez_Ignorada,
  sum(CASE WHEN s.gravidez = 'Duplas' THEN 1 ELSE 0 END) as ctg_gravidez_Dupla,
  sum(CASE WHEN s.gravidez = 'Única' THEN 1 ELSE 0 END) as ctg_gravidez_Unica,
  sum(CASE WHEN s.gravidez = 'Tripla e mais' THEN 1 ELSE 0 END) as ctg_gravidez_Tripla_e_mais,
  (sum(CASE WHEN s.gravidez IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_gravidez_null,
  (sum(CASE WHEN s.gravidez = 'Ignorada' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_gravidez_Ignorada,
  (sum(CASE WHEN s.gravidez = 'Duplas' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_gravidez_Dupla,
  (sum(CASE WHEN s.gravidez = 'Única' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_gravidez_Unica,
  (sum(CASE WHEN s.gravidez = 'Tripla e mais' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_gravidez_Tripla_e_mais,
  sum(CASE WHEN s.parto IS NULL THEN 1 ELSE 0 END) as ctg_parto_null,
  sum(CASE WHEN s.parto = 'Ignorado' THEN 1 ELSE 0 END) as ctg_parto_Ignorado,
  sum(CASE WHEN s.parto = 'Cesáreo' THEN 1 ELSE 0 END) as ctg_parto_Cesareo,
  sum(CASE WHEN s.parto = 'Vaginal' THEN 1 ELSE 0 END) as ctg_parto_Vaginal,
  (sum(CASE WHEN s.parto IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_parto_null,
  (sum(CASE WHEN s.parto = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_parto_Ignorado,
  (sum(CASE WHEN s.parto = 'Cesáreo' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_parto_Cesareo,
  (sum(CASE WHEN s.parto = 'Vaginal' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_parto_Vaginal,
  sum(CASE WHEN s.obitoparto IS NULL THEN 1 ELSE 0 END) as ctg_obitoparto_null,
  sum(CASE WHEN s.obitoparto = 'Antes' THEN 1 ELSE 0 END) as ctg_obitoparto_Antes,
  sum(CASE WHEN s.obitoparto = 'Ignorado' THEN 1 ELSE 0 END) as ctg_obitoparto_Ignorado,
  sum(CASE WHEN s.obitoparto = 'Durante' THEN 1 ELSE 0 END) as ctg_obitoparto_Durante,
  sum(CASE WHEN s.obitoparto = 'Depois' THEN 1 ELSE 0 END) as ctg_obitoparto_Depois,
  (sum(CASE WHEN s.obitoparto IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitoparto_null,
  (sum(CASE WHEN s.obitoparto = 'Antes' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitoparto_Antes,
  (sum(CASE WHEN s.obitoparto = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitoparto_Ignorado,
  (sum(CASE WHEN s.obitoparto = 'Durante' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitoparto_Durante,
  (sum(CASE WHEN s.obitoparto = 'Depois' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitoparto_Depois,
  sum(CASE WHEN s.peso IS NULL THEN 1 ELSE 0 END) as ctg_peso_null,
  AVG(CASE WHEN s.peso IS NULL THEN 1 ELSE 0 END) as media_peso_null,
  AVG(peso) AS media_peso,
  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY peso) AS mediana_peso,
  STDDEV(peso) AS dp_peso,
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY peso) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY peso) AS iiq_peso,
  MAX(peso) AS max_peso,
  MIN(peso) AS min_peso,
  sum(CASE WHEN s.obitograv IS NULL THEN 1 ELSE 0 END) as ctg_obitograv_null,
  sum(CASE WHEN s.obitograv = 'Ignorado' THEN 1 ELSE 0 END) as ctg_obitograv_Ignorado,
  sum(CASE WHEN s.obitograv = 'Sim' THEN 1 ELSE 0 END) as ctg_obitograv_Sim,
  sum(CASE WHEN s.obitograv = 'Não' THEN 1 ELSE 0 END) as ctg_obitograv_Nao,
  (sum(CASE WHEN s.obitograv IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitograv_null,
  (sum(CASE WHEN s.obitograv = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitograv_Ignorado,
  (sum(CASE WHEN s.obitograv = 'Sim' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitograv_Sim,
  (sum(CASE WHEN s.obitograv = 'Não' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitograv_Nao,
  sum(CASE WHEN s.obitopuerp IS NULL THEN 1 ELSE 0 END) as ctg_obitopuerp_null,
  sum(CASE WHEN s.obitopuerp = 'Ignorado' THEN 1 ELSE 0 END) as ctg_obitopuerp_Ignorado,
  sum(CASE WHEN s.obitopuerp = 'Sim, de 43 dias a 1 ano' THEN 1 ELSE 0 END) as ctg_obitopuerp_Sim_de_43_dias_a_1_ano,
  sum(CASE WHEN s.obitopuerp = 'Não' THEN 1 ELSE 0 END) as ctg_obitopuerp_Nao,
  sum(CASE WHEN s.obitopuerp = 'Sim, até 42 dias após o parto' THEN 1 ELSE 0 END) as ctg_obitopuerp_Sim_ate_42_dias_apos_o_parto,
  (sum(CASE WHEN s.obitopuerp IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitopuerp_null,
  (sum(CASE WHEN s.obitopuerp = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitopuerp_Ignorado,
  (sum(CASE WHEN s.obitopuerp = 'Sim, de 43 dias a 1 ano' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitopuerp_Sim_de_43_dias_a_1_ano,
  (sum(CASE WHEN s.obitopuerp = 'Não' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitopuerp_Nao,
  (sum(CASE WHEN s.obitopuerp = 'Sim, até 42 dias após o parto' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_obitopuerp_Sim_ate_42_dias_apos_o_parto,
  sum(CASE WHEN s.assistmed IS NULL THEN 1 ELSE 0 END) as ctg_assistmed_null,
  sum(CASE WHEN s.assistmed = 'Ignorado' THEN 1 ELSE 0 END) as ctg_assistmed_Ignorado,
  sum(CASE WHEN s.assistmed = 'Sim' THEN 1 ELSE 0 END) as ctg_assistmed_Sim,
  sum(CASE WHEN s.assistmed = 'Não' THEN 1 ELSE 0 END) as ctg_assistmed_Nao,
  (sum(CASE WHEN s.assistmed IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_assistmed_null,
  (sum(CASE WHEN s.assistmed = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_assistmed_Ignorado,
  (sum(CASE WHEN s.assistmed = 'Sim' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_assistmed_Sim,
  (sum(CASE WHEN s.assistmed = 'Não' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_assistmed_Nao,
  sum(CASE WHEN s.exame IS NULL THEN 1 ELSE 0 END) as ctg_exame_null,
  sum(CASE WHEN s.exame = 'Ignorado' THEN 1 ELSE 0 END) as ctg_exame_Ignorado,
  sum(CASE WHEN s.exame = 'Sim' THEN 1 ELSE 0 END) as ctg_exame_Sim,
  sum(CASE WHEN s.exame = 'Não' THEN 1 ELSE 0 END) as ctg_exame_Nao,
  (sum(CASE WHEN s.exame IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_exame_null,
  (sum(CASE WHEN s.exame = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_exame_Ignorado,
  (sum(CASE WHEN s.exame = 'Sim' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_exame_Sim,
  (sum(CASE WHEN s.exame = 'Não' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_exame_Nao,
  sum(CASE WHEN s.cirurgia IS NULL THEN 1 ELSE 0 END) as ctg_cirurgia_null,
  sum(CASE WHEN s.cirurgia = 'Ignorado' THEN 1 ELSE 0 END) as ctg_cirurgia_Ignorado,
  sum(CASE WHEN s.cirurgia = 'Sim' THEN 1 ELSE 0 END) as ctg_cirurgia_Sim,
  sum(CASE WHEN s.cirurgia = 'Não' THEN 1 ELSE 0 END) as ctg_cirurgia_Nao,
  (sum(CASE WHEN s.cirurgia IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_cirurgia_null,
  (sum(CASE WHEN s.cirurgia = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_cirurgia_Ignorado,
  (sum(CASE WHEN s.cirurgia = 'Sim' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_cirurgia_Sim,
  (sum(CASE WHEN s.cirurgia = 'Não' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_cirurgia_Nao,
  sum(CASE WHEN s.necropsia IS NULL THEN 1 ELSE 0 END) as ctg_necropsia_null,
  sum(CASE WHEN s.necropsia = 'Ignorado' THEN 1 ELSE 0 END) as ctg_necropsia_Ignorado,
  sum(CASE WHEN s.necropsia = 'Sim' THEN 1 ELSE 0 END) as ctg_necropsia_Sim,
  sum(CASE WHEN s.necropsia = 'Não' THEN 1 ELSE 0 END) as ctg_necropsia_Nao,
  (sum(CASE WHEN s.necropsia IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_necropsia_null,
  (sum(CASE WHEN s.necropsia = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_necropsia_Ignorado,
  (sum(CASE WHEN s.necropsia = 'Sim' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_necropsia_Sim,
  (sum(CASE WHEN s.necropsia = 'Não' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_necropsia_Nao,
  sum(CASE WHEN s.circobito IS NULL THEN 1 ELSE 0 END) as ctg_circobito_null,
  sum(CASE WHEN s.circobito = 'Acidente' THEN 1 ELSE 0 END) as ctg_circobito_Acidente,
  sum(CASE WHEN s.circobito = 'Outros' THEN 1 ELSE 0 END) as ctg_circobito_Outros,
  sum(CASE WHEN s.circobito = 'Ignorado' THEN 1 ELSE 0 END) as ctg_circobito_Ignorado,
  sum(CASE WHEN s.circobito = 'Suicídio' THEN 1 ELSE 0 END) as ctg_circobito_Suicidio,
  sum(CASE WHEN s.circobito = 'Homicídio' THEN 1 ELSE 0 END) as ctg_circobito_Homicidio,
  (sum(CASE WHEN s.circobito IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_circobito_null,
  (sum(CASE WHEN s.circobito = 'Acidente' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_circobito_Acidente,
  (sum(CASE WHEN s.circobito = 'Outros' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_circobito_Outros,
  (sum(CASE WHEN s.circobito = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_circobito_Ignorado,
  (sum(CASE WHEN s.circobito = 'Suicídio' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_circobito_Suicidio,
  (sum(CASE WHEN s.circobito = 'Homicídio' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_circobito_Homicidio,
  sum(CASE WHEN s.acidtrab IS NULL THEN 1 ELSE 0 END) as ctg_acidtrab_null,
  sum(CASE WHEN s.acidtrab = 'Ignorado' THEN 1 ELSE 0 END) as ctg_acidtrab_Ignorado,
  sum(CASE WHEN s.acidtrab = 'Sim' THEN 1 ELSE 0 END) as ctg_acidtrab_Sim,
  sum(CASE WHEN s.acidtrab = 'Não' THEN 1 ELSE 0 END) as ctg_acidtrab_Nao,
  (sum(CASE WHEN s.acidtrab IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_acidtrab_null,
  (sum(CASE WHEN s.acidtrab = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_acidtrab_Ignorado,
  (sum(CASE WHEN s.acidtrab = 'Sim' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_acidtrab_Sim,
  (sum(CASE WHEN s.acidtrab = 'Não' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_acidtrab_Nao,
  sum(CASE WHEN s.fonte IS NULL THEN 1 ELSE 0 END) as ctg_fonte_null,
  sum(CASE WHEN s.fonte = 'Hospital' THEN 1 ELSE 0 END) as ctg_fonte_Hospital,
  sum(CASE WHEN s.fonte = 'Ignorado' THEN 1 ELSE 0 END) as ctg_fonte_Ignorado,
  sum(CASE WHEN s.fonte = 'Ocorrência policial' THEN 1 ELSE 0 END) as ctg_fonte_Ocorrencia_policial,
  sum(CASE WHEN s.fonte = 'Outra' THEN 1 ELSE 0 END) as ctg_fonte_Outra,
  sum(CASE WHEN s.fonte = 'Família' THEN 1 ELSE 0 END) as ctg_fonte_Familia,
  (sum(CASE WHEN s.fonte IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonte_null,
  (sum(CASE WHEN s.fonte = 'Hospital' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonte_Hospital,
  (sum(CASE WHEN s.fonte = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonte_Ignorado,
  (sum(CASE WHEN s.fonte = 'Ocorrência policial' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonte_Ocorrencia_policial,
  (sum(CASE WHEN s.fonte = 'Outra' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonte_Outra,
  (sum(CASE WHEN s.fonte = 'Família' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonte_Familia,
  sum(CASE WHEN s.fonteinv IS NULL THEN 1 ELSE 0 END) as ctg_fonteinv_null,
  sum(CASE WHEN s.fonteinv = 'I M L' THEN 1 ELSE 0 END) as ctg_fonteinv_I_M_L,
  sum(CASE WHEN s.fonteinv = 'Estabelecimento de Saúde / Prontuário' THEN 1 ELSE 0 END) as ctg_fonteinv_Estabelecimento_de_Saude_Prontuaio,
  sum(CASE WHEN s.fonteinv = 'S V O' THEN 1 ELSE 0 END) as ctg_fonteinv_S_V_O,
  sum(CASE WHEN s.fonteinv = 'Relacionado com outros bancos de dados' THEN 1 ELSE 0 END) as ctg_fonteinv_Relacionado_com_outros_bancos_de_dados,
  sum(CASE WHEN s.fonteinv = 'Outra fonte' THEN 1 ELSE 0 END) as ctg_fonteinv_Outra_fonte,
  sum(CASE WHEN s.fonteinv = 'Visita domiciliar / Entrevista família' THEN 1 ELSE 0 END) as ctg_fonteinv_Visita_domiciliar_Entrevista_familia,
  sum(CASE WHEN s.fonteinv = 'Ignorado' THEN 1 ELSE 0 END) as ctg_fonteinv_Ignorado,
  sum(CASE WHEN s.fonteinv = 'Múltiplas fontes' THEN 1 ELSE 0 END) as ctg_fonteinv_Mutiplas_fontes,
  sum(CASE WHEN s.fonteinv = 'Comitê de Morte Materna e/ou Infantil' THEN 1 ELSE 0 END) as ctg_fonteinv_Comite_de_Morte_Materna_e_ou_Infantil,
  (sum(CASE WHEN s.fonteinv IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonteinv_null,
  (sum(CASE WHEN s.fonteinv = 'I M L' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonteinv_I_M_L,
  (sum(CASE WHEN s.fonteinv = 'Estabelecimento de Saúde / Prontuário' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonteinv_Estabelecimento_de_Saude_Prontuaio,
  (sum(CASE WHEN s.fonteinv = 'S V O' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonteinv_S_V_O,
  (sum(CASE WHEN s.fonteinv = 'Relacionado com outros bancos de dados' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonteinv_Relacionado_com_outros_bancos_de_dados,
  (sum(CASE WHEN s.fonteinv = 'Outra fonte' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonteinv_Outra_fonte,
  (sum(CASE WHEN s.fonteinv = 'Visita domiciliar / Entrevista família' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonteinv_Visita_domiciliar_Entrevista_familia,
  (sum(CASE WHEN s.fonteinv = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonteinv_Ignorado,
  (sum(CASE WHEN s.fonteinv = 'Múltiplas fontes' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonteinv_Mutiplas_fontes,
  (sum(CASE WHEN s.fonteinv = 'Comitê de Morte Materna e/ou Infantil' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_fonteinv_Comite_de_Morte_Materna_e_ou_Infantil,
  sum(CASE WHEN s.stdoepidem IS NULL THEN 1 ELSE 0 END) as ctg_stdoepidem_null,
  sum(CASE WHEN s.stdoepidem = 'Sim' THEN 1 ELSE 0 END) as ctg_stdoepidem_Sim,
  sum(CASE WHEN s.stdoepidem = 'Não' THEN 1 ELSE 0 END) as ctg_stdoepidem_Nao,
  (sum(CASE WHEN s.stdoepidem IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_stdoepidem_null,
  (sum(CASE WHEN s.stdoepidem = 'Sim' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_stdoepidem_Sim,
  (sum(CASE WHEN s.stdoepidem = 'Não' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_stdoepidem_Nao,
  sum(CASE WHEN s.stdonova IS NULL THEN 1 ELSE 0 END) as ctg_stdonova_null,
  sum(CASE WHEN s.stdonova = 'Sim' THEN 1 ELSE 0 END) as ctg_stdonova_Sim,
  sum(CASE WHEN s.stdonova = 'Não' THEN 1 ELSE 0 END) as ctg_stdonova_Nao,
  (sum(CASE WHEN s.stdonova IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_stdonova_null,
  (sum(CASE WHEN s.stdonova = 'Sim' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_stdonova_Sim,
  (sum(CASE WHEN s.stdonova = 'Não' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_stdonova_Nao,
  sum(CASE WHEN s.tpobitocor IS NULL THEN 1 ELSE 0 END) as ctg_tpobitocor_null,
  sum(CASE WHEN s.tpobitocor = 'Após o abortamento' THEN 1 ELSE 0 END) as ctg_tpobitocor_Apos_o_abortamento,
  sum(CASE WHEN s.tpobitocor = 'Mais de um ano após o parto' THEN 1 ELSE 0 END) as ctg_tpobitocor_Mais_de_um_ano_apos_o_parto,
  sum(CASE WHEN s.tpobitocor = 'Durante o abortamento' THEN 1 ELSE 0 END) as ctg_tpobitocor_Durante_o_abortamento,
  sum(CASE WHEN s.tpobitocor = 'No puerpério - até 42 dias após o parto' THEN 1 ELSE 0 END) as ctg_tpobitocor_No_puerperio_ate_42_dias_apos_o_parto,
  sum(CASE WHEN s.tpobitocor = 'Durante a gestação' THEN 1 ELSE 0 END) as ctg_tpobitocor_Durante_a_gestacao,
  sum(CASE WHEN s.tpobitocor = 'No parto ou até 1 hora após o parto' THEN 1 ELSE 0 END) as ctg_tpobitocor_No_parto_ou_ate_1_hora_apos_o_parto,
  sum(CASE WHEN s.tpobitocor = 'Entre 43 dias e até 1 ano após o parto' THEN 1 ELSE 0 END) as ctg_tpobitocor_Entre_43_dias_e_ate_1_ano_apos_o_parto,
  sum(CASE WHEN s.tpobitocor = 'O óbito não ocorreu nas circunstâncias anteriores' THEN 1 ELSE 0 END) as ctg_tpobitocor_O_obito_nao_ocorreu_nas_circunstancias_anteriores,
  sum(CASE WHEN s.tpobitocor = 'A investigação não identificou o momento do óbito' THEN 1 ELSE 0 END) as ctg_tpobitocor_A_investigacao_nao_identificou_o_momento_do_obito,
  (sum(CASE WHEN s.tpobitocor IS NULL THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_tpobitocor_null,
  (sum(CASE WHEN s.tpobitocor = 'Após o abortamento' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_tpobitocor_Apos_o_abortamento,
  (sum(CASE WHEN s.tpobitocor = 'Mais de um ano após o parto' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_tpobitocor_Mais_de_um_ano_apos_o_parto,
  (sum(CASE WHEN s.tpobitocor = 'Durante o abortamento' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_tpobitocor_Durante_o_abortamento,
  (sum(CASE WHEN s.tpobitocor = 'No puerpério - até 42 dias após o parto' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_tpobitocor_No_puerperio_ate_42_dias_apos_o_parto,
  (sum(CASE WHEN s.tpobitocor = 'Durante a gestação' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_tpobitocor_Durante_a_gestacao,
  (sum(CASE WHEN s.tpobitocor = 'No parto ou até 1 hora após o parto' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_tpobitocor_No_parto_ou_ate_1_hora_apos_o_parto,
  (sum(CASE WHEN s.tpobitocor = 'Entre 43 dias e até 1 ano após o parto' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_tpobitocor_Entre_43_dias_e_ate_1_ano_apos_o_parto,
  (sum(CASE WHEN s.tpobitocor = 'O óbito não ocorreu nas circunstâncias anteriores' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_tpobitocor_O_obito_nao_ocorreu_nas_circunstancias_anteriores,
  (sum(CASE WHEN s.tpobitocor = 'A investigação não identificou o momento do óbito' THEN 1 ELSE 0 END)::numeric/count(s.sim_id))*100 as pct_tpobitocor_A_investigacao_nao_identificou_o_momento_do_obito
FROM public.sim s 
GROUP BY s.codigo_municipio, s.nu_mes, s.nu_ano)

SELECT 
  r.*,
  t.ctg_day_of_week_Thursday,
  t.ctg_day_of_week_Wednesday,
  t.ctg_day_of_week_Saturday,
  t.ctg_day_of_week_Monday,
  t.ctg_day_of_week_Friday,
  t.ctg_day_of_week_Tuesday,
  t.ctg_day_of_week_Sunday,
  t.pct_day_of_week_Thursday,
  t.pct_day_of_week_Wednesday,
  t.pct_day_of_week_Saturday,
  t.pct_day_of_week_Monday,
  t.pct_day_of_week_Friday,
  t.pct_day_of_week_Tuesday,
  t.pct_day_of_week_Sunday
FROM 
  restante_tabela r
JOIN 
  tabela_dia_semana t
ON 
  r.codigo_municipio = t.codigo_municipio AND
  r.nu_mes = t.nu_mes AND
  r.nu_ano = t.nu_ano;
