CREATE TABLE agrupado.sinan_dengue_agrupado as

with tabela_diferença_dias as (
select 
  f.codigo_municipio,
  f.nu_mes,
  f.nu_ano,
  sum(CASE WHEN f.tempo_ate_interna IS NULL THEN 1 ELSE 0 END) as ctg_tempo_ate_interna_null,
  AVG(CASE WHEN f.tempo_ate_interna IS NULL THEN 1 ELSE 0 END) as media_tempo_ate_interna_null,
  AVG(f.tempo_ate_interna) AS media_tempo_ate_interna,
  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY tempo_ate_interna) AS mediana_tempo_ate_interna,
  STDDEV(f.tempo_ate_interna) AS dp_tempo_ate_interna,
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY tempo_ate_interna) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY tempo_ate_interna) AS iiq_tempo_ate_interna,
  MAX(f.tempo_ate_interna) AS max_tempo_ate_interna,
  MIN(f.tempo_ate_interna) AS min_tempo_ate_interna,
  sum(CASE WHEN f.tempo_ate_invest IS NULL THEN 1 ELSE 0 END) as ctg_tempo_ate_invest_null,
  AVG(CASE WHEN f.tempo_ate_invest IS NULL THEN 1 ELSE 0 END) as media_tempo_ate_invest_null,
  AVG(f.tempo_ate_invest) AS media_tempo_ate_invest,
  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY tempo_ate_invest) AS mediana_tempo_ate_invest,
  STDDEV(f.tempo_ate_invest) AS dp_tempo_ate_invest,
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY tempo_ate_invest) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY tempo_ate_invest) AS iiq_tempo_ate_invest,
  MAX(f.tempo_ate_invest) AS max_tempo_ate_invest,
  MIN(f.tempo_ate_invest) AS min_tempo_ate_invest,
  sum(CASE WHEN f.tempo_ate_ns1 IS NULL THEN 1 ELSE 0 END) as ctg_tempo_ate_ns1_null,
  AVG(CASE WHEN f.tempo_ate_ns1 IS NULL THEN 1 ELSE 0 END) as media_tempo_ate_ns1_null,
  AVG(f.tempo_ate_ns1) AS media_tempo_ate_ns1,
  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY tempo_ate_ns1) AS mediana_tempo_ate_ns1,
  STDDEV(f.tempo_ate_ns1) AS dp_tempo_ate_ns1,
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY tempo_ate_ns1) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY tempo_ate_ns1) AS iiq_tempo_ate_ns1,
  MAX(f.tempo_ate_ns1) AS max_tempo_ate_ns1,
  MIN(f.tempo_ate_ns1) AS min_tempo_ate_ns1,
  sum(CASE WHEN f.tempo_ate_pcr IS NULL THEN 1 ELSE 0 END) as ctg_tempo_ate_pcr_null,
AVG(CASE WHEN f.tempo_ate_pcr IS NULL THEN 1 ELSE 0 END) as media_tempo_ate_pcr_null,
AVG(f.tempo_ate_pcr) AS media_tempo_ate_pcr,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY tempo_ate_pcr) AS mediana_tempo_ate_pcr,
STDDEV(f.tempo_ate_pcr) AS dp_tempo_ate_pcr,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY tempo_ate_pcr) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY tempo_ate_pcr) AS iiq_tempo_ate_pcr,
MAX(f.tempo_ate_pcr) AS max_tempo_ate_pcr,
MIN(f.tempo_ate_pcr) AS min_tempo_ate_pcr,
sum(CASE WHEN f.tempo_ate_soro IS NULL THEN 1 ELSE 0 END) as ctg_tempo_ate_soro_null,
AVG(CASE WHEN f.tempo_ate_soro IS NULL THEN 1 ELSE 0 END) as media_tempo_ate_soro_null,
AVG(f.tempo_ate_soro) AS media_tempo_ate_soro,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY tempo_ate_soro) AS mediana_tempo_ate_soro,
STDDEV(f.tempo_ate_soro) AS dp_tempo_ate_soro,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY tempo_ate_soro) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY tempo_ate_soro) AS iiq_tempo_ate_soro,
MAX(f.tempo_ate_soro) AS max_tempo_ate_soro,
MIN(f.tempo_ate_soro) AS min_tempo_ate_soro,
sum(CASE WHEN f.tempo_ate_viral IS NULL THEN 1 ELSE 0 END) as ctg_tempo_ate_viral_null,
AVG(CASE WHEN f.tempo_ate_viral IS NULL THEN 1 ELSE 0 END) as media_tempo_ate_viral_null,
AVG(f.tempo_ate_viral) AS media_tempo_ate_viral,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY tempo_ate_viral) AS mediana_tempo_ate_viral,
STDDEV(f.tempo_ate_viral) AS dp_tempo_ate_viral,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY tempo_ate_viral) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY tempo_ate_viral) AS iiq_tempo_ate_viral,
MAX(f.tempo_ate_viral) AS max_tempo_ate_viral,
MIN(f.tempo_ate_viral) AS min_tempo_ate_viral,
sum(CASE WHEN f.tempo_ate_obito IS NULL THEN 1 ELSE 0 END) as ctg_tempo_ate_obito_null,
AVG(CASE WHEN f.tempo_ate_obito IS NULL THEN 1 ELSE 0 END) as media_tempo_ate_obito_null,
AVG(f.tempo_ate_obito) AS media_tempo_ate_obito,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY tempo_ate_obito) AS mediana_tempo_ate_obito,
STDDEV(f.tempo_ate_obito) AS dp_tempo_ate_obito,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY tempo_ate_obito) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY tempo_ate_obito) AS iiq_tempo_ate_obito,
MAX(f.tempo_ate_obito) AS max_tempo_ate_obito,
MIN(f.tempo_ate_obito) AS min_tempo_ate_obito,
sum(CASE WHEN f.tempo_ate_alrm IS NULL THEN 1 ELSE 0 END) as ctg_tempo_ate_alrm_null,
AVG(CASE WHEN f.tempo_ate_alrm IS NULL THEN 1 ELSE 0 END) as media_tempo_ate_alrm_null,
AVG(f.tempo_ate_alrm) AS media_tempo_ate_alrm,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY tempo_ate_alrm) AS mediana_tempo_ate_alrm,
STDDEV(f.tempo_ate_alrm) AS dp_tempo_ate_alrm,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY tempo_ate_alrm) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY tempo_ate_alrm) AS iiq_tempo_ate_alrm,
MAX(f.tempo_ate_alrm) AS max_tempo_ate_alrm,
MIN(f.tempo_ate_alrm) AS min_tempo_ate_alrm,
sum(CASE WHEN f.tempo_ate_grav IS NULL THEN 1 ELSE 0 END) as ctg_tempo_ate_grav_null,
AVG(CASE WHEN f.tempo_ate_grav IS NULL THEN 1 ELSE 0 END) as media_tempo_ate_grav_null,
AVG(f.tempo_ate_grav) AS media_tempo_ate_grav,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY tempo_ate_grav) AS mediana_tempo_ate_grav,
STDDEV(f.tempo_ate_grav) AS dp_tempo_ate_grav,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY tempo_ate_grav) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY tempo_ate_grav) AS iiq_tempo_ate_grav,
MAX(f.tempo_ate_grav) AS max_tempo_ate_grav,
MIN(f.tempo_ate_grav) AS min_tempo_ate_grav,
sum(CASE WHEN f.tempo_ate_chik_s1 IS NULL THEN 1 ELSE 0 END) as ctg_tempo_ate_chik_s1_null,
AVG(CASE WHEN f.tempo_ate_chik_s1 IS NULL THEN 1 ELSE 0 END) as media_tempo_ate_chik_s1_null,
AVG(f.tempo_ate_chik_s1) AS media_tempo_ate_chik_s1,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY tempo_ate_chik_s1) AS mediana_tempo_ate_chik_s1,
STDDEV(f.tempo_ate_chik_s1) AS dp_tempo_ate_chik_s1,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY tempo_ate_chik_s1) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY tempo_ate_chik_s1) AS iiq_tempo_ate_chik_s1,
MAX(f.tempo_ate_chik_s1) AS max_tempo_ate_chik_s1,
MIN(f.tempo_ate_chik_s1) AS min_tempo_ate_chik_s1,
sum(CASE WHEN f.tempo_ate_chik_s2 IS NULL THEN 1 ELSE 0 END) as ctg_tempo_ate_chik_s2_null,
AVG(CASE WHEN f.tempo_ate_chik_s2 IS NULL THEN 1 ELSE 0 END) as media_tempo_ate_chik_s2_null,
AVG(f.tempo_ate_chik_s2) AS media_tempo_ate_chik_s2,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY tempo_ate_chik_s2) AS mediana_tempo_ate_chik_s2,
STDDEV(f.tempo_ate_chik_s2) AS dp_tempo_ate_chik_s2,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY tempo_ate_chik_s2) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY tempo_ate_chik_s2) AS iiq_tempo_ate_chik_s2,
MAX(f.tempo_ate_chik_s2) AS max_tempo_ate_chik_s2,
MIN(f.tempo_ate_chik_s2) AS min_tempo_ate_chik_s2
from
(select
  sd.id_municip as codigo_municipio,
  sd.nu_mes,
  sd.nu_ano,
  (dt_interna - dt_sin_pri) as tempo_ate_interna,
  (dt_invest - dt_sin_pri) as tempo_ate_invest,
  (dt_ns1 - dt_sin_pri) as tempo_ate_ns1,
  (dt_pcr - dt_sin_pri) as tempo_ate_pcr,
  (dt_soro - dt_sin_pri) as tempo_ate_soro,
  (dt_viral - dt_sin_pri) as tempo_ate_viral,
  (dt_obito - dt_sin_pri) as tempo_ate_obito,
  (dt_alrm - dt_sin_pri) as tempo_ate_alrm,
  (dt_grav - dt_sin_pri) as tempo_ate_grav,
  (dt_chik_s1 - dt_sin_pri) as tempo_ate_chik_s1,
  (dt_chik_s2 - dt_sin_pri) as tempo_ate_chik_s2
from public.sinan_dengue sd) as f
group by f.codigo_municipio, f.nu_mes, f.nu_ano),

restante_tabela as (
SELECT 
  sd.id_municip as codigo_municipio,
  sd.nu_mes,
  sd.nu_ano,
sum(CASE WHEN sd.evolucao IS NULL THEN 1 ELSE 0 END) as ctg_evolucao_null,
sum(CASE WHEN sd.evolucao = 'ignorado' THEN 1 ELSE 0 END) as ctg_evolucao_ignorado,
sum(CASE WHEN sd.evolucao = 'óbito por dengue' THEN 1 ELSE 0 END) as ctg_evolucao_obito_dengue,
sum(CASE WHEN sd.evolucao = 'cura' THEN 1 ELSE 0 END) as ctg_evolucao_cura,
sum(CASE WHEN sd.evolucao = 'óbito por outras causas' THEN 1 ELSE 0 END) as ctg_evolucao_obito_outras_causas,
sum(CASE WHEN sd.evolucao = 'óbito em investigação' THEN 1 ELSE 0 END) as ctg_evolucao_obito_investigacao,
(sum(CASE WHEN sd.evolucao IS NULL THEN 1 ELSE 0 END)::numeric / count(sd.sinan_id)) * 100 as pct_evolucao_null,
(sum(CASE WHEN sd.evolucao = 'ignorado' THEN 1 ELSE 0 END)::numeric / count(sd.sinan_id)) * 100 as pct_evolucao_ignorado,
(sum(CASE WHEN sd.evolucao = 'óbito por dengue' THEN 1 ELSE 0 END)::numeric / count(sd.sinan_id)) * 100 as pct_evolucao_obito_dengue,
(sum(CASE WHEN sd.evolucao = 'cura' THEN 1 ELSE 0 END)::numeric / count(sd.sinan_id)) * 100 as pct_evolucao_cura,
(sum(CASE WHEN sd.evolucao = 'óbito por outras causas' THEN 1 ELSE 0 END)::numeric / count(sd.sinan_id)) * 100 as pct_evolucao_obito_outras_causas,
(sum(CASE WHEN sd.evolucao = 'óbito em investigação' THEN 1 ELSE 0 END)::numeric / count(sd.sinan_id)) * 100 as pct_evolucao_obito_investigacao,
  sum(CASE WHEN sd.classi_fin IS NULL THEN 1 ELSE 0 END) as ctg_classi_fin_null,
  sum(CASE WHEN sd.classi_fin = 'Dengue' THEN 1 ELSE 0 END) as ctg_classi_fin_Dengue,
  sum(CASE WHEN sd.classi_fin = 'Descartado' THEN 1 ELSE 0 END) as ctg_classi_fin_Descartado,
  sum(CASE WHEN sd.classi_fin = 'Dengue com sinais de alarme' THEN 1 ELSE 0 END) as ctg_classi_fin_Dengue_com_sinais_de_alarme,
  sum(CASE WHEN sd.classi_fin = 'Dengue grave' THEN 1 ELSE 0 END) as ctg_classi_fin_Dengue_grave,
  (sum(CASE WHEN sd.classi_fin IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_classi_fin_null,
  (sum(CASE WHEN sd.classi_fin = 'Dengue' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_classi_fin_Dengue,
  (sum(CASE WHEN sd.classi_fin = 'Descartado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_classi_fin_Descartado,
  (sum(CASE WHEN sd.classi_fin = 'Dengue com sinais de alarme' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_classi_fin_Dengue_com_sinais_de_alarme,
  (sum(CASE WHEN sd.classi_fin = 'Dengue grave' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_classi_fin_Dengue_grave,
  sum(CASE WHEN sd.uf IS NULL THEN 1 ELSE 0 END) as ctg_uf_null,
  sum(CASE WHEN sd.uf = '12' THEN 1 ELSE 0 END) as ctg_uf_12,
  sum(CASE WHEN sd.uf = '13' THEN 1 ELSE 0 END) as ctg_uf_13,
  sum(CASE WHEN sd.uf = '28' THEN 1 ELSE 0 END) as ctg_uf_28,
  sum(CASE WHEN sd.uf = '15' THEN 1 ELSE 0 END) as ctg_uf_15,
  sum(CASE WHEN sd.uf = '52' THEN 1 ELSE 0 END) as ctg_uf_52,
  sum(CASE WHEN sd.uf = '23' THEN 1 ELSE 0 END) as ctg_uf_23,
  sum(CASE WHEN sd.uf = '14' THEN 1 ELSE 0 END) as ctg_uf_14,
  sum(CASE WHEN sd.uf = '25' THEN 1 ELSE 0 END) as ctg_uf_25,
  sum(CASE WHEN sd.uf = '32' THEN 1 ELSE 0 END) as ctg_uf_32,
  sum(CASE WHEN sd.uf = '29' THEN 1 ELSE 0 END) as ctg_uf_29,
  sum(CASE WHEN sd.uf = '21' THEN 1 ELSE 0 END) as ctg_uf_21,
  sum(CASE WHEN sd.uf = '24' THEN 1 ELSE 0 END) as ctg_uf_24,
  sum(CASE WHEN sd.uf = '33' THEN 1 ELSE 0 END) as ctg_uf_33,
  sum(CASE WHEN sd.uf = '17' THEN 1 ELSE 0 END) as ctg_uf_17,
  sum(CASE WHEN sd.uf = '35' THEN 1 ELSE 0 END) as ctg_uf_35,
  sum(CASE WHEN sd.uf = '41' THEN 1 ELSE 0 END) as ctg_uf_41,
  sum(CASE WHEN sd.uf = '22' THEN 1 ELSE 0 END) as ctg_uf_22,
  sum(CASE WHEN sd.uf = '51' THEN 1 ELSE 0 END) as ctg_uf_51,
  sum(CASE WHEN sd.uf = '53' THEN 1 ELSE 0 END) as ctg_uf_53,
  sum(CASE WHEN sd.uf = '27' THEN 1 ELSE 0 END) as ctg_uf_27,
  sum(CASE WHEN sd.uf = '11' THEN 1 ELSE 0 END) as ctg_uf_11,
  sum(CASE WHEN sd.uf = '31' THEN 1 ELSE 0 END) as ctg_uf_31,
  sum(CASE WHEN sd.uf = '50' THEN 1 ELSE 0 END) as ctg_uf_50,
  sum(CASE WHEN sd.uf = '43' THEN 1 ELSE 0 END) as ctg_uf_43,
  sum(CASE WHEN sd.uf = '16' THEN 1 ELSE 0 END) as ctg_uf_16,
  sum(CASE WHEN sd.uf = '42' THEN 1 ELSE 0 END) as ctg_uf_42,
  sum(CASE WHEN sd.uf = '26' THEN 1 ELSE 0 END) as ctg_uf_26,
  (sum(CASE WHEN sd.uf IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_null,
  (sum(CASE WHEN sd.uf = '12' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_12,
  (sum(CASE WHEN sd.uf = '13' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_13,
  (sum(CASE WHEN sd.uf = '28' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_28,
  (sum(CASE WHEN sd.uf = '15' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_15,
  (sum(CASE WHEN sd.uf = '52' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_52,
  (sum(CASE WHEN sd.uf = '23' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_23,
  (sum(CASE WHEN sd.uf = '14' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_14,
  (sum(CASE WHEN sd.uf = '25' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_25,
  (sum(CASE WHEN sd.uf = '32' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_32,
  (sum(CASE WHEN sd.uf = '29' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_29,
  (sum(CASE WHEN sd.uf = '21' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_21,
  (sum(CASE WHEN sd.uf = '24' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_24,
  (sum(CASE WHEN sd.uf = '33' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_33,
  (sum(CASE WHEN sd.uf = '17' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_17,
  (sum(CASE WHEN sd.uf = '35' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_35,
  (sum(CASE WHEN sd.uf = '41' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_41,
  (sum(CASE WHEN sd.uf = '22' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_22,
  (sum(CASE WHEN sd.uf = '51' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_51,
  (sum(CASE WHEN sd.uf = '53' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_53,
  (sum(CASE WHEN sd.uf = '27' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_27,
  (sum(CASE WHEN sd.uf = '11' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_11,
  (sum(CASE WHEN sd.uf = '31' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_31,
  (sum(CASE WHEN sd.uf = '50' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_50,
  (sum(CASE WHEN sd.uf = '43' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_43,
  (sum(CASE WHEN sd.uf = '16' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_16,
  (sum(CASE WHEN sd.uf = '42' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_42,
  (sum(CASE WHEN sd.uf = '26' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_uf_26,
  sum(CASE WHEN sd.criterio IS NULL THEN 1 ELSE 0 END) as ctg_criterio_null,
  sum(CASE WHEN sd.criterio = 'Clínico Epidemiológico' THEN 1 ELSE 0 END) as ctg_criterio_Clinico_Epidemiologico,
  sum(CASE WHEN sd.criterio = 'Laboratório' THEN 1 ELSE 0 END) as ctg_criterio_Laboratorio,
  sum(CASE WHEN sd.criterio = 'Em investigação' THEN 1 ELSE 0 END) as ctg_criterio_Em_investigacao,
  (sum(CASE WHEN sd.criterio IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_criterio_null,
  (sum(CASE WHEN sd.criterio = 'Clínico Epidemiológico' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_criterio_Clinico_Epidemiologico,
  (sum(CASE WHEN sd.criterio = 'Laboratório' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_criterio_Laboratorio,
  (sum(CASE WHEN sd.criterio = 'Em investigação' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_criterio_Em_investigacao,
  sum(CASE WHEN sd.cs_escol_n IS NULL THEN 1 ELSE 0 END) as ctg_cs_escol_n_null,
  sum(CASE WHEN sd.cs_escol_n = 'Ensino médio incompleto (antigo colegial ou 2° grau)' THEN 1 ELSE 0 END) as ctg_cs_escol_n_Ensino_medio_incompleto_antigo_colegial_ou_2_grau,
  sum(CASE WHEN sd.cs_escol_n = '1ª a 4ª série incompleta do EF' THEN 1 ELSE 0 END) as ctg_cs_escol_n_1a_a_4a_serie_incompleta_do_EF,
  sum(CASE WHEN sd.cs_escol_n = 'Ignorado' THEN 1 ELSE 0 END) as ctg_cs_escol_n_Ignorado,
  sum(CASE WHEN sd.cs_escol_n = 'Não se aplica' THEN 1 ELSE 0 END) as ctg_cs_escol_n_Nao_se_aplica,
  sum(CASE WHEN sd.cs_escol_n = 'Ensino médio completo (antigo colegial ou 2° grau)' THEN 1 ELSE 0 END) as ctg_cs_escol_n_Ensino_medio_completo_antigo_colegial_ou_2_grau,
  sum(CASE WHEN sd.cs_escol_n = '4ª série completa do EF (antigo 1° grau)' THEN 1 ELSE 0 END) as ctg_cs_escol_n_4a_serie_completa_do_EF_antigo_1_grau,
  sum(CASE WHEN sd.cs_escol_n = '5ª à 8ª série incompleta do EF (antigo ginásio ou 1° grau)' THEN 1 ELSE 0 END) as ctg_cs_escol_n_5a_a_8a_serie_incompleta_do_EF_antigo_ginasio_ou_1_grau,
  sum(CASE WHEN sd.cs_escol_n = 'Educação superior completa' THEN 1 ELSE 0 END) as ctg_cs_escol_n_Educacao_superior_completa,
  sum(CASE WHEN sd.cs_escol_n = 'Educação superior incompleta' THEN 1 ELSE 0 END) as ctg_cs_escol_n_Educacao_superior_incompleta,
  sum(CASE WHEN sd.cs_escol_n = 'Ensino fundamental completo (antigo ginásio ou 1° grau)' THEN 1 ELSE 0 END) as ctg_cs_escol_n_Ensino_fundamental_completo_antigo_ginasio_ou_1_grau,
  (sum(CASE WHEN sd.cs_escol_n IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_escol_n_null,
  (sum(CASE WHEN sd.cs_escol_n = 'Ensino médio incompleto (antigo colegial ou 2° grau)' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_escol_n_Ensino_medio_incompleto_antigo_colegial_ou_2_grau,
  (sum(CASE WHEN sd.cs_escol_n = '1ª a 4ª série incompleta do EF' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_escol_n_1a_a_4a_serie_incompleta_do_EF,
  (sum(CASE WHEN sd.cs_escol_n = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_escol_n_Ignorado,
  (sum(CASE WHEN sd.cs_escol_n = 'Não se aplica' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_escol_n_Nao_se_aplica,
  (sum(CASE WHEN sd.cs_escol_n = 'Ensino médio completo (antigo colegial ou 2° grau)' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_escol_n_Ensino_medio_completo_antigo_colegial_ou_2_grau,
  (sum(CASE WHEN sd.cs_escol_n = '4ª série completa do EF (antigo 1° grau)' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_escol_n_4a_serie_completa_do_EF_antigo_1_grau,
  (sum(CASE WHEN sd.cs_escol_n = '5ª à 8ª série incompleta do EF (antigo ginásio ou 1° grau)' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_escol_n_5a_a_8a_serie_incompleta_do_EF_antigo_ginasio_ou_1_grau,
  (sum(CASE WHEN sd.cs_escol_n = 'Educação superior completa' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_escol_n_Educacao_superior_completa,
  (sum(CASE WHEN sd.cs_escol_n = 'Educação superior incompleta' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_escol_n_Educacao_superior_incompleta,
  (sum(CASE WHEN sd.cs_escol_n = 'Ensino fundamental completo (antigo ginásio ou 1° grau)' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_escol_n_Ensino_fundamental_completo_antigo_ginasio_ou_1_grau,
  sum(CASE WHEN sd.cs_gestant IS NULL THEN 1 ELSE 0 END) as ctg_cs_gestant_null,
  sum(CASE WHEN sd.cs_gestant = 'Ignorado' THEN 1 ELSE 0 END) as ctg_cs_gestant_Ignorado,
  sum(CASE WHEN sd.cs_gestant = 'Não se aplica' THEN 1 ELSE 0 END) as ctg_cs_gestant_Nao_se_aplica,
  sum(CASE WHEN sd.cs_gestant = 'Não' THEN 1 ELSE 0 END) as ctg_cs_gestant_Nao,
  sum(CASE WHEN sd.cs_gestant = '3º Trimestre' THEN 1 ELSE 0 END) as ctg_cs_gestant_3o_Trimestre,
  sum(CASE WHEN sd.cs_gestant = 'Idade gestacional ignorada' THEN 1 ELSE 0 END) as ctg_cs_gestant_Idade_gestacional_ignorada,
  sum(CASE WHEN sd.cs_gestant = '1º Trimestre' THEN 1 ELSE 0 END) as ctg_cs_gestant_1o_Trimestre,
  sum(CASE WHEN sd.cs_gestant = '2º Trimestre' THEN 1 ELSE 0 END) as ctg_cs_gestant_2o_Trimestre,
  (sum(CASE WHEN sd.cs_gestant IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_gestant_null,
  (sum(CASE WHEN sd.cs_gestant = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_gestant_Ignorado,
  (sum(CASE WHEN sd.cs_gestant = 'Não se aplica' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_gestant_Nao_se_aplica,
  (sum(CASE WHEN sd.cs_gestant = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_gestant_Nao,
  (sum(CASE WHEN sd.cs_gestant = '3º Trimestre' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_gestant_3o_Trimestre,
  (sum(CASE WHEN sd.cs_gestant = 'Idade gestacional ignorada' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_gestant_Idade_gestacional_ignorada,
  (sum(CASE WHEN sd.cs_gestant = '1º Trimestre' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_gestant_1o_Trimestre,
  (sum(CASE WHEN sd.cs_gestant = '2º Trimestre' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_gestant_2o_Trimestre,
    sum(CASE WHEN sd.cs_raca IS NULL THEN 1 ELSE 0 END) as ctg_cs_raca_null,
  sum(CASE WHEN sd.cs_raca = 'Ignorado' THEN 1 ELSE 0 END) as ctg_cs_raca_Ignorado,
  sum(CASE WHEN sd.cs_raca = 'indígena' THEN 1 ELSE 0 END) as ctg_cs_raca_indigena,
  sum(CASE WHEN sd.cs_raca = 'parda' THEN 1 ELSE 0 END) as ctg_cs_raca_parda,
  sum(CASE WHEN sd.cs_raca = 'branca' THEN 1 ELSE 0 END) as ctg_cs_raca_branca,
  sum(CASE WHEN sd.cs_raca = 'amarela' THEN 1 ELSE 0 END) as ctg_cs_raca_amarela,
  sum(CASE WHEN sd.cs_raca = 'preta' THEN 1 ELSE 0 END) as ctg_cs_raca_preta,
  (sum(CASE WHEN sd.cs_raca IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_raca_null,
  (sum(CASE WHEN sd.cs_raca = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_raca_Ignorado,
  (sum(CASE WHEN sd.cs_raca = 'indígena' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_raca_indigena,
  (sum(CASE WHEN sd.cs_raca = 'parda' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_raca_parda,
  (sum(CASE WHEN sd.cs_raca = 'branca' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_raca_branca,
  (sum(CASE WHEN sd.cs_raca = 'amarela' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_raca_amarela,
  (sum(CASE WHEN sd.cs_raca = 'preta' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_raca_preta,
  sum(CASE WHEN sd.cs_sexo IS NULL THEN 1 ELSE 0 END) as ctg_cs_sexo_null,
sum(CASE WHEN sd.cs_sexo = 'Feminino' THEN 1 ELSE 0 END) as ctg_cs_sexo_Feminino,
sum(CASE WHEN sd.cs_sexo = 'Ignorado' THEN 1 ELSE 0 END) as ctg_cs_sexo_Ignorado,
sum(CASE WHEN sd.cs_sexo = 'Masculino' THEN 1 ELSE 0 END) as ctg_cs_sexo_Masculino,
(sum(CASE WHEN sd.cs_sexo IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_sexo_null,
(sum(CASE WHEN sd.cs_sexo = 'Feminino' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_sexo_Feminino,
(sum(CASE WHEN sd.cs_sexo = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_sexo_Ignorado,
(sum(CASE WHEN sd.cs_sexo = 'Masculino' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cs_sexo_Masculino,
sum(CASE WHEN sd.artralgia IS NULL THEN 1 ELSE 0 END) as ctg_artralgia_null,
sum(CASE WHEN sd.artralgia = 'Sim' THEN 1 ELSE 0 END) as ctg_artralgia_Sim,
sum(CASE WHEN sd.artralgia = 'Não' THEN 1 ELSE 0 END) as ctg_artralgia_Nao,
(sum(CASE WHEN sd.artralgia IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_artralgia_null,
(sum(CASE WHEN sd.artralgia = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_artralgia_Sim,
(sum(CASE WHEN sd.artralgia = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_artralgia_Nao,
sum(CASE WHEN sd.artrite IS NULL THEN 1 ELSE 0 END) as ctg_artrite_null,
sum(CASE WHEN sd.artrite = 'Sim' THEN 1 ELSE 0 END) as ctg_artrite_Sim,
sum(CASE WHEN sd.artrite = 'Não' THEN 1 ELSE 0 END) as ctg_artrite_Nao,
(sum(CASE WHEN sd.artrite IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_artrite_null,
(sum(CASE WHEN sd.artrite = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_artrite_Sim,
(sum(CASE WHEN sd.artrite = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_artrite_Nao,
sum(CASE WHEN sd.auto_imune IS NULL THEN 1 ELSE 0 END) as ctg_auto_imune_null,
sum(CASE WHEN sd.auto_imune = 'Sim' THEN 1 ELSE 0 END) as ctg_auto_imune_Sim,
sum(CASE WHEN sd.auto_imune = 'Não' THEN 1 ELSE 0 END) as ctg_auto_imune_Nao,
(sum(CASE WHEN sd.auto_imune IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_auto_imune_null,
(sum(CASE WHEN sd.auto_imune = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_auto_imune_Sim,
(sum(CASE WHEN sd.auto_imune = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_auto_imune_Nao,
sum(CASE WHEN sd.cefaleia IS NULL THEN 1 ELSE 0 END) as ctg_cefaleia_null,
sum(CASE WHEN sd.cefaleia = 'Sim' THEN 1 ELSE 0 END) as ctg_cefaleia_Sim,
sum(CASE WHEN sd.cefaleia = 'Não' THEN 1 ELSE 0 END) as ctg_cefaleia_Nao,
(sum(CASE WHEN sd.cefaleia IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cefaleia_null,
(sum(CASE WHEN sd.cefaleia = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cefaleia_Sim,
(sum(CASE WHEN sd.cefaleia = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_cefaleia_Nao,
sum(CASE WHEN sd.conjuntvit IS NULL THEN 1 ELSE 0 END) as ctg_conjuntvit_null,
sum(CASE WHEN sd.conjuntvit = 'Sim' THEN 1 ELSE 0 END) as ctg_conjuntvit_Sim,
sum(CASE WHEN sd.conjuntvit = 'Não' THEN 1 ELSE 0 END) as ctg_conjuntvit_Nao,
(sum(CASE WHEN sd.conjuntvit IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_conjuntvit_null,
(sum(CASE WHEN sd.conjuntvit = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_conjuntvit_Sim,
(sum(CASE WHEN sd.conjuntvit = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_conjuntvit_Nao,
sum(CASE WHEN sd.diabetes IS NULL THEN 1 ELSE 0 END) as ctg_diabetes_null,
sum(CASE WHEN sd.diabetes = 'Sim' THEN 1 ELSE 0 END) as ctg_diabetes_Sim,
sum(CASE WHEN sd.diabetes = 'Não' THEN 1 ELSE 0 END) as ctg_diabetes_Nao,
(sum(CASE WHEN sd.diabetes IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_diabetes_null,
(sum(CASE WHEN sd.diabetes = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_diabetes_Sim,
(sum(CASE WHEN sd.diabetes = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_diabetes_Nao,
sum(CASE WHEN sd.dor_costas IS NULL THEN 1 ELSE 0 END) as ctg_dor_costas_null,
sum(CASE WHEN sd.dor_costas = 'Sim' THEN 1 ELSE 0 END) as ctg_dor_costas_Sim,
sum(CASE WHEN sd.dor_costas = 'Não' THEN 1 ELSE 0 END) as ctg_dor_costas_Nao,
(sum(CASE WHEN sd.dor_costas IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_dor_costas_null,
(sum(CASE WHEN sd.dor_costas = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_dor_costas_Sim,
(sum(CASE WHEN sd.dor_costas = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_dor_costas_Nao,
sum(CASE WHEN sd.dor_retro IS NULL THEN 1 ELSE 0 END) as ctg_dor_retro_null,
sum(CASE WHEN sd.dor_retro = 'Sim' THEN 1 ELSE 0 END) as ctg_dor_retro_Sim,
sum(CASE WHEN sd.dor_retro = 'Não' THEN 1 ELSE 0 END) as ctg_dor_retro_Nao,
(sum(CASE WHEN sd.dor_retro IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_dor_retro_null,
(sum(CASE WHEN sd.dor_retro = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_dor_retro_Sim,
(sum(CASE WHEN sd.dor_retro = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_dor_retro_Nao,
sum(CASE WHEN sd.histopa_n IS NULL THEN 1 ELSE 0 END) as ctg_histopa_n_null,
sum(CASE WHEN sd.histopa_n = 'Positivo' THEN 1 ELSE 0 END) as ctg_histopa_n_Positivo,
sum(CASE WHEN sd.histopa_n = 'Não realizado' THEN 1 ELSE 0 END) as ctg_histopa_n_Nao_realizado,
sum(CASE WHEN sd.histopa_n = 'Inconclusivo' THEN 1 ELSE 0 END) as ctg_histopa_n_Inconclusivo,
sum(CASE WHEN sd.histopa_n = 'Negativo' THEN 1 ELSE 0 END) as ctg_histopa_n_Negativo,
(sum(CASE WHEN sd.histopa_n IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_histopa_n_null,
(sum(CASE WHEN sd.histopa_n = 'Positivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_histopa_n_Positivo,
(sum(CASE WHEN sd.histopa_n = 'Não realizado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_histopa_n_Nao_realizado,
(sum(CASE WHEN sd.histopa_n = 'Inconclusivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_histopa_n_Inconclusivo,
(sum(CASE WHEN sd.histopa_n = 'Negativo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_histopa_n_Negativo,
sum(CASE WHEN sd.imunoh_n IS NULL THEN 1 ELSE 0 END) as ctg_imunoh_n_null,
sum(CASE WHEN sd.imunoh_n = 'Positivo' THEN 1 ELSE 0 END) as ctg_imunoh_n_Positivo,
sum(CASE WHEN sd.imunoh_n = 'Não realizado' THEN 1 ELSE 0 END) as ctg_imunoh_n_Nao_realizado,
sum(CASE WHEN sd.imunoh_n = 'Inconclusivo' THEN 1 ELSE 0 END) as ctg_imunoh_n_Inconclusivo,
sum(CASE WHEN sd.imunoh_n = 'Negativo' THEN 1 ELSE 0 END) as ctg_imunoh_n_Negativo,
(sum(CASE WHEN sd.imunoh_n IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_imunoh_n_null,
(sum(CASE WHEN sd.imunoh_n = 'Positivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_imunoh_n_Positivo,
(sum(CASE WHEN sd.imunoh_n = 'Não realizado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_imunoh_n_Nao_realizado,
(sum(CASE WHEN sd.imunoh_n = 'Inconclusivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_imunoh_n_Inconclusivo,
(sum(CASE WHEN sd.imunoh_n = 'Negativo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_imunoh_n_Negativo,
sum(CASE WHEN sd.hospitaliz IS NULL THEN 1 ELSE 0 END) as ctg_hospitaliz_null,
sum(CASE WHEN sd.hospitaliz = 'Ignorado' THEN 1 ELSE 0 END) as ctg_hospitaliz_Ignorado,
sum(CASE WHEN sd.hospitaliz = 'Sim' THEN 1 ELSE 0 END) as ctg_hospitaliz_Sim,
sum(CASE WHEN sd.hospitaliz = 'Não' THEN 1 ELSE 0 END) as ctg_hospitaliz_Nao,
(sum(CASE WHEN sd.hospitaliz IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hospitaliz_null,
(sum(CASE WHEN sd.hospitaliz = 'Ignorado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hospitaliz_Ignorado,
(sum(CASE WHEN sd.hospitaliz = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hospitaliz_Sim,
(sum(CASE WHEN sd.hospitaliz = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hospitaliz_Nao,
sum(CASE WHEN sd.exantema IS NULL THEN 1 ELSE 0 END) as ctg_exantema_null,
(sum(CASE WHEN sd.exantema IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_exantema_null,
sum(CASE WHEN sd.exantema = 'Sim' THEN 1 ELSE 0 END) as ctg_exantema_Sim,
(sum(CASE WHEN sd.exantema = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_exantema_Sim,
sum(CASE WHEN sd.exantema = 'Não' THEN 1 ELSE 0 END) as ctg_exantema_Nao,
(sum(CASE WHEN sd.exantema = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_exantema_Nao,
sum(CASE WHEN sd.febre IS NULL THEN 1 ELSE 0 END) as ctg_febre_null,
(sum(CASE WHEN sd.febre IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_febre_null,
sum(CASE WHEN sd.febre = 'Sim' THEN 1 ELSE 0 END) as ctg_febre_Sim,
(sum(CASE WHEN sd.febre = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_febre_Sim,
sum(CASE WHEN sd.febre = 'Não' THEN 1 ELSE 0 END) as ctg_febre_Nao,
(sum(CASE WHEN sd.febre = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_febre_Nao,
sum(CASE WHEN sd.hematolog IS NULL THEN 1 ELSE 0 END) as ctg_hematolog_null,
(sum(CASE WHEN sd.hematolog IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hematolog_null,
sum(CASE WHEN sd.hematolog = 'Sim' THEN 1 ELSE 0 END) as ctg_hematolog_Sim,
(sum(CASE WHEN sd.hematolog = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hematolog_Sim,
sum(CASE WHEN sd.hematolog = 'Não' THEN 1 ELSE 0 END) as ctg_hematolog_Nao,
(sum(CASE WHEN sd.hematolog = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hematolog_Nao,
sum(CASE WHEN sd.hepatopat IS NULL THEN 1 ELSE 0 END) as ctg_hepatopat_null,
(sum(CASE WHEN sd.hepatopat IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hepatopat_null,
sum(CASE WHEN sd.hepatopat = 'Sim' THEN 1 ELSE 0 END) as ctg_hepatopat_Sim,
(sum(CASE WHEN sd.hepatopat = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hepatopat_Sim,
sum(CASE WHEN sd.hepatopat = 'Não' THEN 1 ELSE 0 END) as ctg_hepatopat_Nao,
(sum(CASE WHEN sd.hepatopat = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hepatopat_Nao,
sum(CASE WHEN sd.hipertensa IS NULL THEN 1 ELSE 0 END) as ctg_hipertensa_null,
(sum(CASE WHEN sd.hipertensa IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hipertensa_null,
sum(CASE WHEN sd.hipertensa = 'Sim' THEN 1 ELSE 0 END) as ctg_hipertensa_Sim,
(sum(CASE WHEN sd.hipertensa = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hipertensa_Sim,
sum(CASE WHEN sd.hipertensa = 'Não' THEN 1 ELSE 0 END) as ctg_hipertensa_Nao,
(sum(CASE WHEN sd.hipertensa = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_hipertensa_Nao,
sum(CASE WHEN sd.laco IS NULL THEN 1 ELSE 0 END) as ctg_laco_null,
(sum(CASE WHEN sd.laco IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_laco_null,
sum(CASE WHEN sd.laco = 'Sim' THEN 1 ELSE 0 END) as ctg_laco_Sim,
(sum(CASE WHEN sd.laco = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_laco_Sim,
sum(CASE WHEN sd.laco = 'Não' THEN 1 ELSE 0 END) as ctg_laco_Nao,
(sum(CASE WHEN sd.laco = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_laco_Nao,
sum(CASE WHEN sd.leucopenia IS NULL THEN 1 ELSE 0 END) as ctg_leucopenia_null,
(sum(CASE WHEN sd.leucopenia IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_leucopenia_null,
sum(CASE WHEN sd.leucopenia = 'Sim' THEN 1 ELSE 0 END) as ctg_leucopenia_Sim,
(sum(CASE WHEN sd.leucopenia = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_leucopenia_Sim,
sum(CASE WHEN sd.leucopenia = 'Não' THEN 1 ELSE 0 END) as ctg_leucopenia_Nao,
(sum(CASE WHEN sd.leucopenia = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_leucopenia_Nao,
sum(CASE WHEN sd.mialgia IS NULL THEN 1 ELSE 0 END) as ctg_mialgia_null,
(sum(CASE WHEN sd.mialgia IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_mialgia_null,
sum(CASE WHEN sd.mialgia = 'Sim' THEN 1 ELSE 0 END) as ctg_mialgia_Sim,
(sum(CASE WHEN sd.mialgia = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_mialgia_Sim,
sum(CASE WHEN sd.mialgia = 'Não' THEN 1 ELSE 0 END) as ctg_mialgia_Nao,
(sum(CASE WHEN sd.mialgia = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_mialgia_Nao,
sum(CASE WHEN sd.nausea IS NULL THEN 1 ELSE 0 END) as ctg_nausea_null,
(sum(CASE WHEN sd.nausea IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_nausea_null,
sum(CASE WHEN sd.nausea = 'Sim' THEN 1 ELSE 0 END) as ctg_nausea_Sim,
(sum(CASE WHEN sd.nausea = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_nausea_Sim,
sum(CASE WHEN sd.nausea = 'Não' THEN 1 ELSE 0 END) as ctg_nausea_Nao,
(sum(CASE WHEN sd.nausea = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_nausea_Nao,
sum(CASE WHEN sd.petequia_n IS NULL THEN 1 ELSE 0 END) as ctg_petequia_n_null,
(sum(CASE WHEN sd.petequia_n IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_petequia_n_null,
sum(CASE WHEN sd.petequia_n = 'Sim' THEN 1 ELSE 0 END) as ctg_petequia_n_Sim,
(sum(CASE WHEN sd.petequia_n = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_petequia_n_Sim,
sum(CASE WHEN sd.petequia_n = 'Não' THEN 1 ELSE 0 END) as ctg_petequia_n_Nao,
(sum(CASE WHEN sd.petequia_n = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_petequia_n_Nao,
sum(CASE WHEN sd.vomito IS NULL THEN 1 ELSE 0 END) as ctg_vomito_null,
(sum(CASE WHEN sd.vomito IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_vomito_null,
sum(CASE WHEN sd.vomito = 'Sim' THEN 1 ELSE 0 END) as ctg_vomito_Sim,
(sum(CASE WHEN sd.vomito = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_vomito_Sim,
sum(CASE WHEN sd.vomito = 'Não' THEN 1 ELSE 0 END) as ctg_vomito_Nao,
(sum(CASE WHEN sd.vomito = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_vomito_Nao,
sum(CASE WHEN sd.renal IS NULL THEN 1 ELSE 0 END) as ctg_renal_null,
(sum(CASE WHEN sd.renal IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_renal_null,
sum(CASE WHEN sd.renal = 'Sim' THEN 1 ELSE 0 END) as ctg_renal_Sim,
(sum(CASE WHEN sd.renal = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_renal_Sim,
sum(CASE WHEN sd.renal = 'Não' THEN 1 ELSE 0 END) as ctg_renal_Nao,
(sum(CASE WHEN sd.renal = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_renal_Nao,
sum(CASE WHEN sd.resul_ns1 IS NULL THEN 1 ELSE 0 END) as ctg_resul_ns1_null,
sum(CASE WHEN sd.resul_ns1 = 'Positivo' THEN 1 ELSE 0 END) as ctg_resul_ns1_Positivo,
sum(CASE WHEN sd.resul_ns1 = 'Não realizado' THEN 1 ELSE 0 END) as ctg_resul_ns1_Nao_realizado,
sum(CASE WHEN sd.resul_ns1 = 'Inconclusivo' THEN 1 ELSE 0 END) as ctg_resul_ns1_Inconclusivo,
sum(CASE WHEN sd.resul_ns1 = 'Negativo' THEN 1 ELSE 0 END) as ctg_resul_ns1_Negativo,
(sum(CASE WHEN sd.resul_ns1 IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_ns1_null,
(sum(CASE WHEN sd.resul_ns1 = 'Positivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_ns1_Positivo,
(sum(CASE WHEN sd.resul_ns1 = 'Não realizado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_ns1_Nao_realizado,
(sum(CASE WHEN sd.resul_ns1 = 'Inconclusivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_ns1_Inconclusivo,
(sum(CASE WHEN sd.resul_ns1 = 'Negativo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_ns1_Negativo,
sum(CASE WHEN sd.resul_pcr_ IS NULL THEN 1 ELSE 0 END) as ctg_resul_pcr_null,
sum(CASE WHEN sd.resul_pcr_ = 'Positivo' THEN 1 ELSE 0 END) as ctg_resul_pcr_Positivo,
sum(CASE WHEN sd.resul_pcr_ = 'Não realizado' THEN 1 ELSE 0 END) as ctg_resul_pcr_Nao_realizado,
sum(CASE WHEN sd.resul_pcr_ = 'Inconclusivo' THEN 1 ELSE 0 END) as ctg_resul_pcr_Inconclusivo,
sum(CASE WHEN sd.resul_pcr_ = 'Negativo' THEN 1 ELSE 0 END) as ctg_resul_pcr_Negativo,
(sum(CASE WHEN sd.resul_pcr_ IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_pcr_null,
(sum(CASE WHEN sd.resul_pcr_ = 'Positivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_pcr_Positivo,
(sum(CASE WHEN sd.resul_pcr_ = 'Não realizado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_pcr_Nao_realizado,
(sum(CASE WHEN sd.resul_pcr_ = 'Inconclusivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_pcr_Inconclusivo,
(sum(CASE WHEN sd.resul_pcr_ = 'Negativo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_pcr_Negativo,
sum(CASE WHEN sd.resul_soro IS NULL THEN 1 ELSE 0 END) as ctg_resul_soro_null,
sum(CASE WHEN sd.resul_soro = 'Reagente' THEN 1 ELSE 0 END) as ctg_resul_soro_Reagente,
sum(CASE WHEN sd.resul_soro = 'Não realizado' THEN 1 ELSE 0 END) as ctg_resul_soro_Nao_realizado,
sum(CASE WHEN sd.resul_soro = 'Inconclusivo' THEN 1 ELSE 0 END) as ctg_resul_soro_Inconclusivo,
sum(CASE WHEN sd.resul_soro = 'Não Reagente' THEN 1 ELSE 0 END) as ctg_resul_soro_Nao_Reagente,
(sum(CASE WHEN sd.resul_soro IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_soro_null,
(sum(CASE WHEN sd.resul_soro = 'Reagente' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_soro_Reagente,
(sum(CASE WHEN sd.resul_soro = 'Não realizado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_soro_Nao_realizado,
(sum(CASE WHEN sd.resul_soro = 'Inconclusivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_soro_Inconclusivo,
(sum(CASE WHEN sd.resul_soro = 'Não Reagente' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_soro_Nao_Reagente,
sum(CASE WHEN sd.resul_vi_n IS NULL THEN 1 ELSE 0 END) as ctg_resul_vi_n_null,
sum(CASE WHEN sd.resul_vi_n = 'Positivo' THEN 1 ELSE 0 END) as ctg_resul_vi_n_Positivo,
sum(CASE WHEN sd.resul_vi_n = 'Não realizado' THEN 1 ELSE 0 END) as ctg_resul_vi_n_Nao_realizado,
sum(CASE WHEN sd.resul_vi_n = 'Inconclusivo' THEN 1 ELSE 0 END) as ctg_resul_vi_n_Inconclusivo,
sum(CASE WHEN sd.resul_vi_n = 'Negativo' THEN 1 ELSE 0 END) as ctg_resul_vi_n_Negativo,
(sum(CASE WHEN sd.resul_vi_n IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_vi_n_null,
(sum(CASE WHEN sd.resul_vi_n = 'Positivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_vi_n_Positivo,
(sum(CASE WHEN sd.resul_vi_n = 'Não realizado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_vi_n_Nao_realizado,
(sum(CASE WHEN sd.resul_vi_n = 'Inconclusivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_vi_n_Inconclusivo,
(sum(CASE WHEN sd.resul_vi_n = 'Negativo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_vi_n_Negativo,
sum(CASE WHEN sd.resul_prnt IS NULL THEN 1 ELSE 0 END) as ctg_resul_prnt_null,
sum(CASE WHEN sd.resul_prnt = 'Reagente' THEN 1 ELSE 0 END) as ctg_resul_prnt_Reagente,
sum(CASE WHEN sd.resul_prnt = 'Não realizado' THEN 1 ELSE 0 END) as ctg_resul_prnt_Nao_realizado,
sum(CASE WHEN sd.resul_prnt = 'Inconclusivo' THEN 1 ELSE 0 END) as ctg_resul_prnt_Inconclusivo,
sum(CASE WHEN sd.resul_prnt = 'Não Reagente' THEN 1 ELSE 0 END) as ctg_resul_prnt_Nao_Reagente,
(sum(CASE WHEN sd.resul_prnt IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_prnt_null,
(sum(CASE WHEN sd.resul_prnt = 'Reagente' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_prnt_Reagente,
(sum(CASE WHEN sd.resul_prnt = 'Não realizado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_prnt_Nao_realizado,
(sum(CASE WHEN sd.resul_prnt = 'Inconclusivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_prnt_Inconclusivo,
(sum(CASE WHEN sd.resul_prnt = 'Não Reagente' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_resul_prnt_Nao_Reagente,
sum(CASE WHEN sd.sorotipo IS NULL THEN 1 ELSE 0 END) as ctg_sorotipo_null,
sum(CASE WHEN sd.sorotipo = 'DEN 1' THEN 1 ELSE 0 END) as ctg_sorotipo_DEN_1,
sum(CASE WHEN sd.sorotipo = 'DEN 3' THEN 1 ELSE 0 END) as ctg_sorotipo_DEN_3,
sum(CASE WHEN sd.sorotipo = 'DEN 2' THEN 1 ELSE 0 END) as ctg_sorotipo_DEN_2,
sum(CASE WHEN sd.sorotipo = 'DEN 4' THEN 1 ELSE 0 END) as ctg_sorotipo_DEN_4,
(sum(CASE WHEN sd.sorotipo IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_sorotipo_null,
(sum(CASE WHEN sd.sorotipo = 'DEN 1' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_sorotipo_DEN_1,
(sum(CASE WHEN sd.sorotipo = 'DEN 3' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_sorotipo_DEN_3,
(sum(CASE WHEN sd.sorotipo = 'DEN 2' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_sorotipo_DEN_2,
(sum(CASE WHEN sd.sorotipo = 'DEN 4' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_sorotipo_DEN_4,
sum(CASE WHEN sd.tpautocto IS NULL THEN 1 ELSE 0 END) as ctg_tpautocto_null,
sum(CASE WHEN sd.tpautocto = 'Sim' THEN 1 ELSE 0 END) as ctg_tpautocto_Sim,
sum(CASE WHEN sd.tpautocto = 'Indeterminado' THEN 1 ELSE 0 END) as ctg_tpautocto_Indeterminado,
sum(CASE WHEN sd.tpautocto = 'Não' THEN 1 ELSE 0 END) as ctg_tpautocto_Nao,
(sum(CASE WHEN sd.tpautocto IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_tpautocto_null,
(sum(CASE WHEN sd.tpautocto = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_tpautocto_Sim,
(sum(CASE WHEN sd.tpautocto = 'Indeterminado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_tpautocto_Indeterminado,
(sum(CASE WHEN sd.tpautocto = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_tpautocto_Nao,
sum(CASE WHEN sd.acido_pept IS NULL THEN 1 ELSE 0 END) as ctg_acido_pept_null,
sum(CASE WHEN sd.acido_pept = 'Sim' THEN 1 ELSE 0 END) as ctg_acido_pept_Sim,
sum(CASE WHEN sd.acido_pept = 'Não' THEN 1 ELSE 0 END) as ctg_acido_pept_Nao,
(sum(CASE WHEN sd.acido_pept IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_acido_pept_null,
(sum(CASE WHEN sd.acido_pept = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_acido_pept_Sim,
(sum(CASE WHEN sd.acido_pept = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_acido_pept_Nao,
sum(CASE WHEN sd.alrm_abdom IS NULL THEN 1 ELSE 0 END) as ctg_alrm_abdom_null,
sum(CASE WHEN sd.alrm_abdom = 'Sim' THEN 1 ELSE 0 END) as ctg_alrm_abdom_Sim,
sum(CASE WHEN sd.alrm_abdom = 'Não' THEN 1 ELSE 0 END) as ctg_alrm_abdom_Nao,
(sum(CASE WHEN sd.alrm_abdom IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_abdom_null,
(sum(CASE WHEN sd.alrm_abdom = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_abdom_Sim,
(sum(CASE WHEN sd.alrm_abdom = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_abdom_Nao,
sum(CASE WHEN sd.alrm_hemat IS NULL THEN 1 ELSE 0 END) as ctg_alrm_hemat_null,
sum(CASE WHEN sd.alrm_hemat = 'Sim' THEN 1 ELSE 0 END) as ctg_alrm_hemat_Sim,
sum(CASE WHEN sd.alrm_hemat = 'Não' THEN 1 ELSE 0 END) as ctg_alrm_hemat_Nao,
(sum(CASE WHEN sd.alrm_hemat IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_hemat_null,
(sum(CASE WHEN sd.alrm_hemat = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_hemat_Sim,
(sum(CASE WHEN sd.alrm_hemat = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_hemat_Nao,
sum(CASE WHEN sd.alrm_hepat IS NULL THEN 1 ELSE 0 END) as ctg_alrm_hepat_null,
sum(CASE WHEN sd.alrm_hepat = 'Sim' THEN 1 ELSE 0 END) as ctg_alrm_hepat_Sim,
sum(CASE WHEN sd.alrm_hepat = 'Não' THEN 1 ELSE 0 END) as ctg_alrm_hepat_Nao,
(sum(CASE WHEN sd.alrm_hepat IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_hepat_null,
(sum(CASE WHEN sd.alrm_hepat = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_hepat_Sim,
(sum(CASE WHEN sd.alrm_hepat = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_hepat_Nao,
sum(CASE WHEN sd.alrm_hipot IS NULL THEN 1 ELSE 0 END) as ctg_alrm_hipot_null,
sum(CASE WHEN sd.alrm_hipot = 'Sim' THEN 1 ELSE 0 END) as ctg_alrm_hipot_Sim,
sum(CASE WHEN sd.alrm_hipot = 'Não' THEN 1 ELSE 0 END) as ctg_alrm_hipot_Nao,
(sum(CASE WHEN sd.alrm_hipot IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_hipot_null,
(sum(CASE WHEN sd.alrm_hipot = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_hipot_Sim,
(sum(CASE WHEN sd.alrm_hipot = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_hipot_Nao,
sum(CASE WHEN sd.alrm_letar IS NULL THEN 1 ELSE 0 END) as ctg_alrm_letar_null,
sum(CASE WHEN sd.alrm_letar = 'Sim' THEN 1 ELSE 0 END) as ctg_alrm_letar_Sim,
sum(CASE WHEN sd.alrm_letar = 'Não' THEN 1 ELSE 0 END) as ctg_alrm_letar_Nao,
(sum(CASE WHEN sd.alrm_letar IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_letar_null,
(sum(CASE WHEN sd.alrm_letar = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_letar_Sim,
(sum(CASE WHEN sd.alrm_letar = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_letar_Nao,
sum(CASE WHEN sd.alrm_liq IS NULL THEN 1 ELSE 0 END) as ctg_alrm_liq_null,
sum(CASE WHEN sd.alrm_liq = 'Sim' THEN 1 ELSE 0 END) as ctg_alrm_liq_Sim,
sum(CASE WHEN sd.alrm_liq = 'Não' THEN 1 ELSE 0 END) as ctg_alrm_liq_Nao,
(sum(CASE WHEN sd.alrm_liq IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_liq_null,
(sum(CASE WHEN sd.alrm_liq = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_liq_Sim,
(sum(CASE WHEN sd.alrm_liq = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_liq_Nao,
sum(CASE WHEN sd.alrm_plaq IS NULL THEN 1 ELSE 0 END) as ctg_alrm_plaq_null,
sum(CASE WHEN sd.alrm_plaq = 'Sim' THEN 1 ELSE 0 END) as ctg_alrm_plaq_Sim,
sum(CASE WHEN sd.alrm_plaq = 'Não' THEN 1 ELSE 0 END) as ctg_alrm_plaq_Nao,
(sum(CASE WHEN sd.alrm_plaq IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_plaq_null,
(sum(CASE WHEN sd.alrm_plaq = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_plaq_Sim,
(sum(CASE WHEN sd.alrm_plaq = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_plaq_Nao,
sum(CASE WHEN sd.alrm_sang IS NULL THEN 1 ELSE 0 END) as ctg_alrm_sang_null,
sum(CASE WHEN sd.alrm_sang = 'Sim' THEN 1 ELSE 0 END) as ctg_alrm_sang_Sim,
sum(CASE WHEN sd.alrm_sang = 'Não' THEN 1 ELSE 0 END) as ctg_alrm_sang_Nao,
(sum(CASE WHEN sd.alrm_sang IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_sang_null,
(sum(CASE WHEN sd.alrm_sang = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_sang_Sim,
(sum(CASE WHEN sd.alrm_sang = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_sang_Nao,
sum(CASE WHEN sd.alrm_vom IS NULL THEN 1 ELSE 0 END) as ctg_alrm_vom_null,
sum(CASE WHEN sd.alrm_vom = 'Sim' THEN 1 ELSE 0 END) as ctg_alrm_vom_Sim,
sum(CASE WHEN sd.alrm_vom = 'Não' THEN 1 ELSE 0 END) as ctg_alrm_vom_Nao,
(sum(CASE WHEN sd.alrm_vom IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_vom_null,
(sum(CASE WHEN sd.alrm_vom = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_vom_Sim,
(sum(CASE WHEN sd.alrm_vom = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_alrm_vom_Nao,
sum(CASE WHEN sd.grav_ast IS NULL THEN 1 ELSE 0 END) as ctg_grav_ast_null,
sum(CASE WHEN sd.grav_ast = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_ast_Sim,
sum(CASE WHEN sd.grav_ast = 'Não' THEN 1 ELSE 0 END) as ctg_grav_ast_Nao,
(sum(CASE WHEN sd.grav_ast IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_ast_null,
(sum(CASE WHEN sd.grav_ast = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_ast_Sim,
(sum(CASE WHEN sd.grav_ast = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_ast_Nao,
sum(CASE WHEN sd.grav_consc IS NULL THEN 1 ELSE 0 END) as ctg_grav_consc_null,
sum(CASE WHEN sd.grav_consc = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_consc_Sim,
sum(CASE WHEN sd.grav_consc = 'Não' THEN 1 ELSE 0 END) as ctg_grav_consc_Nao,
(sum(CASE WHEN sd.grav_consc IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_consc_null,
(sum(CASE WHEN sd.grav_consc = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_consc_Sim,
(sum(CASE WHEN sd.grav_consc = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_consc_Nao,
sum(CASE WHEN sd.grav_conv IS NULL THEN 1 ELSE 0 END) as ctg_grav_conv_null,
sum(CASE WHEN sd.grav_conv = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_conv_Sim,
sum(CASE WHEN sd.grav_conv = 'Não' THEN 1 ELSE 0 END) as ctg_grav_conv_Nao,
(sum(CASE WHEN sd.grav_conv IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_conv_null,
(sum(CASE WHEN sd.grav_conv = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_conv_Sim,
(sum(CASE WHEN sd.grav_conv = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_conv_Nao,
sum(CASE WHEN sd.grav_ench IS NULL THEN 1 ELSE 0 END) as ctg_grav_ench_null,
sum(CASE WHEN sd.grav_ench = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_ench_Sim,
sum(CASE WHEN sd.grav_ench = 'Não' THEN 1 ELSE 0 END) as ctg_grav_ench_Nao,
(sum(CASE WHEN sd.grav_ench IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_ench_null,
(sum(CASE WHEN sd.grav_ench = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_ench_Sim,
(sum(CASE WHEN sd.grav_ench = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_ench_Nao,
sum(CASE WHEN sd.grav_extre IS NULL THEN 1 ELSE 0 END) as ctg_grav_extre_null,
sum(CASE WHEN sd.grav_extre = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_extre_Sim,
sum(CASE WHEN sd.grav_extre = 'Não' THEN 1 ELSE 0 END) as ctg_grav_extre_Nao,
(sum(CASE WHEN sd.grav_extre IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_extre_null,
(sum(CASE WHEN sd.grav_extre = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_extre_Sim,
(sum(CASE WHEN sd.grav_extre = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_extre_Nao,
sum(CASE WHEN sd.grav_hemat IS NULL THEN 1 ELSE 0 END) as ctg_grav_hemat_null,
sum(CASE WHEN sd.grav_hemat = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_hemat_Sim,
sum(CASE WHEN sd.grav_hemat = 'Não' THEN 1 ELSE 0 END) as ctg_grav_hemat_Nao,
(sum(CASE WHEN sd.grav_hemat IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_hemat_null,
(sum(CASE WHEN sd.grav_hemat = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_hemat_Sim,
(sum(CASE WHEN sd.grav_hemat = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_hemat_Nao,
sum(CASE WHEN sd.grav_hipot IS NULL THEN 1 ELSE 0 END) as ctg_grav_hipot_null,
sum(CASE WHEN sd.grav_hipot = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_hipot_Sim,
sum(CASE WHEN sd.grav_hipot = 'Não' THEN 1 ELSE 0 END) as ctg_grav_hipot_Nao,
(sum(CASE WHEN sd.grav_hipot IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_hipot_null,
(sum(CASE WHEN sd.grav_hipot = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_hipot_Sim,
(sum(CASE WHEN sd.grav_hipot = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_hipot_Nao,
sum(CASE WHEN sd.grav_insuf IS NULL THEN 1 ELSE 0 END) as ctg_grav_insuf_null,
sum(CASE WHEN sd.grav_insuf = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_insuf_Sim,
sum(CASE WHEN sd.grav_insuf = 'Não' THEN 1 ELSE 0 END) as ctg_grav_insuf_Nao,
(sum(CASE WHEN sd.grav_insuf IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_insuf_null,
(sum(CASE WHEN sd.grav_insuf = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_insuf_Sim,
(sum(CASE WHEN sd.grav_insuf = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_insuf_Nao,
sum(CASE WHEN sd.grav_melen IS NULL THEN 1 ELSE 0 END) as ctg_grav_melen_null,
sum(CASE WHEN sd.grav_melen = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_melen_Sim,
sum(CASE WHEN sd.grav_melen = 'Não' THEN 1 ELSE 0 END) as ctg_grav_melen_Nao,
(sum(CASE WHEN sd.grav_melen IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_melen_null,
(sum(CASE WHEN sd.grav_melen = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_melen_Sim,
(sum(CASE WHEN sd.grav_melen = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_melen_Nao,
sum(CASE WHEN sd.grav_metro IS NULL THEN 1 ELSE 0 END) as ctg_grav_metro_null,
sum(CASE WHEN sd.grav_metro = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_metro_Sim,
sum(CASE WHEN sd.grav_metro = 'Não' THEN 1 ELSE 0 END) as ctg_grav_metro_Nao,
(sum(CASE WHEN sd.grav_metro IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_metro_null,
(sum(CASE WHEN sd.grav_metro = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_metro_Sim,
(sum(CASE WHEN sd.grav_metro = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_metro_Nao,
sum(CASE WHEN sd.grav_mioc IS NULL THEN 1 ELSE 0 END) as ctg_grav_mioc_null,
sum(CASE WHEN sd.grav_mioc = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_mioc_Sim,
sum(CASE WHEN sd.grav_mioc = 'Não' THEN 1 ELSE 0 END) as ctg_grav_mioc_Nao,
(sum(CASE WHEN sd.grav_mioc IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_mioc_null,
(sum(CASE WHEN sd.grav_mioc = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_mioc_Sim,
(sum(CASE WHEN sd.grav_mioc = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_mioc_Nao,
sum(CASE WHEN sd.grav_orgao IS NULL THEN 1 ELSE 0 END) as ctg_grav_orgao_null,
sum(CASE WHEN sd.grav_orgao = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_orgao_Sim,
sum(CASE WHEN sd.grav_orgao = 'Não' THEN 1 ELSE 0 END) as ctg_grav_orgao_Nao,
(sum(CASE WHEN sd.grav_orgao IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_orgao_null,
(sum(CASE WHEN sd.grav_orgao = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_orgao_Sim,
(sum(CASE WHEN sd.grav_orgao = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_orgao_Nao,
sum(CASE WHEN sd.grav_pulso IS NULL THEN 1 ELSE 0 END) as ctg_grav_pulso_null,
sum(CASE WHEN sd.grav_pulso = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_pulso_Sim,
sum(CASE WHEN sd.grav_pulso = 'Não' THEN 1 ELSE 0 END) as ctg_grav_pulso_Nao,
(sum(CASE WHEN sd.grav_pulso IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_pulso_null,
(sum(CASE WHEN sd.grav_pulso = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_pulso_Sim,
(sum(CASE WHEN sd.grav_pulso = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_pulso_Nao,
sum(CASE WHEN sd.grav_sang IS NULL THEN 1 ELSE 0 END) as ctg_grav_sang_null,
sum(CASE WHEN sd.grav_sang = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_sang_Sim,
sum(CASE WHEN sd.grav_sang = 'Não' THEN 1 ELSE 0 END) as ctg_grav_sang_Nao,
(sum(CASE WHEN sd.grav_sang IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_sang_null,
(sum(CASE WHEN sd.grav_sang = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_sang_Sim,
(sum(CASE WHEN sd.grav_sang = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_sang_Nao,
sum(CASE WHEN sd.grav_taqui IS NULL THEN 1 ELSE 0 END) as ctg_grav_taqui_null,
sum(CASE WHEN sd.grav_taqui = 'Sim' THEN 1 ELSE 0 END) as ctg_grav_taqui_Sim,
sum(CASE WHEN sd.grav_taqui = 'Não' THEN 1 ELSE 0 END) as ctg_grav_taqui_Nao,
(sum(CASE WHEN sd.grav_taqui IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_taqui_null,
(sum(CASE WHEN sd.grav_taqui = 'Sim' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_taqui_Sim,
(sum(CASE WHEN sd.grav_taqui = 'Não' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_grav_taqui_Nao,
sum(CASE WHEN sd.res_chiks1 = 'Não Reagente' THEN 1 ELSE 0 END) as ctg_res_chiks1_Nao_Reagente,
sum(CASE WHEN sd.res_chiks1 IS NULL THEN 1 ELSE 0 END) as ctg_res_chiks1_null,
sum(CASE WHEN sd.res_chiks1 = 'Não realizado' THEN 1 ELSE 0 END) as ctg_res_chiks1_Nao_realizado,
sum(CASE WHEN sd.res_chiks1 = 'Reagente' THEN 1 ELSE 0 END) as ctg_res_chiks1_Reagente,
sum(CASE WHEN sd.res_chiks1 = 'Inconclusivo' THEN 1 ELSE 0 END) as ctg_res_chiks1_Inconclusivo,
(sum(CASE WHEN sd.res_chiks1 = 'Não Reagente' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_res_chiks1_Nao_Reagente,
(sum(CASE WHEN sd.res_chiks1 IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_res_chiks1_null,
(sum(CASE WHEN sd.res_chiks1 = 'Não realizado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_res_chiks1_Nao_realizado,
(sum(CASE WHEN sd.res_chiks1 = 'Reagente' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_res_chiks1_Reagente,
(sum(CASE WHEN sd.res_chiks1 = 'Inconclusivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_res_chiks1_Inconclusivo,
sum(CASE WHEN sd.res_chiks2 = 'Não Reagente' THEN 1 ELSE 0 END) as ctg_res_chiks2_Nao_Reagente,
sum(CASE WHEN sd.res_chiks2 IS NULL THEN 1 ELSE 0 END) as ctg_res_chiks2_null,
sum(CASE WHEN sd.res_chiks2 = 'Não realizado' THEN 1 ELSE 0 END) as ctg_res_chiks2_Nao_realizado,
sum(CASE WHEN sd.res_chiks2 = 'Reagente' THEN 1 ELSE 0 END) as ctg_res_chiks2_Reagente,
sum(CASE WHEN sd.res_chiks2 = 'Inconclusivo' THEN 1 ELSE 0 END) as ctg_res_chiks2_Inconclusivo,
(sum(CASE WHEN sd.res_chiks2 = 'Não Reagente' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_res_chiks2_Nao_Reagente,
(sum(CASE WHEN sd.res_chiks2 IS NULL THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_res_chiks2_null,
(sum(CASE WHEN sd.res_chiks2 = 'Não realizado' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_res_chiks2_Nao_realizado,
(sum(CASE WHEN sd.res_chiks2 = 'Reagente' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_res_chiks2_Reagente,
(sum(CASE WHEN sd.res_chiks2 = 'Inconclusivo' THEN 1 ELSE 0 END)::numeric/count(sd.sinan_id))*100 as pct_res_chiks2_Inconclusivo,
  sum(CASE WHEN idade_anos IS NULL THEN 1 ELSE 0 END) as ctg_idade_anos_null,
  AVG(CASE WHEN idade_anos IS NULL THEN 1 ELSE 0 END) as media_idade_anos_null,
  AVG(idade_anos) AS media_idade_anos,
  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY idade_anos) AS mediana_idade_anos,
  STDDEV(idade_anos) AS dp_idade_anos,
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY idade_anos) - PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY idade_anos) AS iiq_idade_anos,
  MAX(idade_anos) AS max_idade_anos,
  MIN(idade_anos) AS min_idade_anos
  FROM public.sinan_dengue sd 
GROUP BY codigo_municipio, nu_mes, nu_ano)

SELECT 
  r.*,
t.media_tempo_ate_interna,
t.mediana_tempo_ate_interna,
t.dp_tempo_ate_interna,
t.iiq_tempo_ate_interna,
t.min_tempo_ate_interna,
t.max_tempo_ate_interna,
t.media_tempo_ate_invest,
t.mediana_tempo_ate_invest,
t.dp_tempo_ate_invest,
t.iiq_tempo_ate_invest,
t.min_tempo_ate_invest,
t.max_tempo_ate_invest,
t.media_tempo_ate_ns1,
t.mediana_tempo_ate_ns1,
t.dp_tempo_ate_ns1,
t.iiq_tempo_ate_ns1,
t.min_tempo_ate_ns1,
t.max_tempo_ate_ns1,
t.media_tempo_ate_pcr,
t.mediana_tempo_ate_pcr,
t.dp_tempo_ate_pcr,
t.iiq_tempo_ate_pcr,
t.min_tempo_ate_pcr,
t.max_tempo_ate_pcr,
t.media_tempo_ate_soro,
t.mediana_tempo_ate_soro,
t.dp_tempo_ate_soro,
t.iiq_tempo_ate_soro,
t.min_tempo_ate_soro,
t.max_tempo_ate_soro,
t.media_tempo_ate_viral,
t.mediana_tempo_ate_viral,
t.dp_tempo_ate_viral,
t.iiq_tempo_ate_viral,
t.min_tempo_ate_viral,
t.max_tempo_ate_viral,
t.media_tempo_ate_obito,
t.mediana_tempo_ate_obito,
t.dp_tempo_ate_obito,
t.iiq_tempo_ate_obito,
t.min_tempo_ate_obito,
t.max_tempo_ate_obito,
t.media_tempo_ate_alrm,
t.mediana_tempo_ate_alrm,
t.dp_tempo_ate_alrm,
t.iiq_tempo_ate_alrm,
t.min_tempo_ate_alrm,
t.max_tempo_ate_alrm,
t.media_tempo_ate_grav,
t.mediana_tempo_ate_grav,
t.dp_tempo_ate_grav,
t.iiq_tempo_ate_grav,
t.min_tempo_ate_grav,
t.max_tempo_ate_grav,
t.media_tempo_ate_chik_s1,
t.mediana_tempo_ate_chik_s1,
t.dp_tempo_ate_chik_s1,
t.iiq_tempo_ate_chik_s1,
t.min_tempo_ate_chik_s1,
t.max_tempo_ate_chik_s1,
t.media_tempo_ate_chik_s2,
t.mediana_tempo_ate_chik_s2,
t.dp_tempo_ate_chik_s2,
t.iiq_tempo_ate_chik_s2,
t.min_tempo_ate_chik_s2,
t.max_tempo_ate_chik_s2
FROM 
  restante_tabela r
JOIN 
  tabela_diferença_dias t
ON 
  r.codigo_municipio = t.codigo_municipio AND
  r.nu_mes = t.nu_mes AND
  r.nu_ano = t.nu_ano;